### PR TITLE
[roseus_mongo/CMakeLists.txt] install test directory

### PR DESCRIPTION
**Pull request by furushchev**

### CODE REVIEW

**Comment by furushchev** [comment]
waiting https://github.com/strands-project/mongodb_store/pull/175

I wonder why test before this passes without this problem...

**Comment by furushchev** [comment]
strands-project/mongodb_store#175 was now merged.
asked release.

**Comment by k-okada** [comment]
> install test directory

is this correct description?

**Comment by furushchev** [comment]
@k-okada At first, yes. `jsk_travis` also checks results of test after install by `grep *.test`. In this part tests for only hydro are also executed. So I renamed the extension of the test only for hydro.

**Comment by furushchev** [comment]
Another problem is in this repo also we check with ROS release repo. (not only shadow fixed)
The test of this pull request will not be success until next ROS stable release.

**Comment by furushchev** [comment]
**MEMO** Please merge #492 first.

**Comment by k-okada** [comment]
#492 seems failing...

--
◉ Kei Okada


2016-11-29 21:02 GMT+09:00 Furushchev <notifications@github.com>:

**Comment by furushchev** [comment]
@k-okada thank you for notification. restarted travis on #492

**Comment by furushchev** [comment]
**MEMO** need to change jsk_travis

**Comment by k-okada** [comment]
https://api.travis-ci.org/jobs/199492463/log.txt?deansi=true

**Comment by furushchev** [comment]
I think it is no more necessary because launch file for testing mongodb with test mode is provided from `mongodb_store` package.

**Pull request closed without merging**
