### PR TITLE
add more option to eusobj->marker-msg

### PR DESCRIPTION
**Pull request by k-okada**
- [euslisp/roseus-utils.l] support bodyset object
- [euslisp/roseus-utils.l] support random color
- [euslisp/roseus-utils.l] support object with :glvertices

### CODE REVIEW

**Comment by k-okada** [comment]
this will optputs

screenshot from 2015-05-01 22 02 19

with

```
(load "pod-lowres.l")
(pod-init)
(objects (list *pod*))

(ros::roseus "hoge")
(ros::advertise "/pod" visualization_msgs::Marker 5)
(setq msg (eusobj->marker-msg  *pod* (instance std_msgs::header :init
                                                :stamp (ros::time-now)
                                                :frame_id "/pod")
                               :lifetime 0
                               :rainbow t))
(ros::publish "/pod" msg)
(ros::spin-once)

```

cc @aginika

**Comment by aginika** [comment]
@k-okada  Thank you! We want to use this as soon as possible!

**Comment by aginika** [comment]
@k-okada 
Hmm.... Where is my fault?
Is the pod as same as yours?

pod


I did below , but the pod seems to be odd...
```
(defun publish-pod ()
  (let ((*simulator-origin* "base"))
    (if (not (boundp '*tfb*)) (setq *tfb* (instance ros::transform-broadcaster :init)))
    (send *tfb* :send-transform (make-coords) "base" "pod")

    (ros::advertise "/pod" visualization_msgs::Marker 5)
    (setq msg (eusobj->marker-msg  *pod* (instance std_msgs::header :init
                                                   :stamp (ros::time-now)
                                                   :frame_id "/pod")
                                   :lifetime 0
                                   :rainbow t))
    (ros::publish "/pod" msg)

```

**Comment by k-okada** [comment]
sorry we need https://github.com/start-jsk/2014-semi/pull/336

--
◉ Kei Okada

**Comment by aginika** [comment]
@k-okada Thank you so much !!
pod_rviz

**Pull request merged**
