### PR TITLE
(ros::tf-transform->coords) failed with with geometry_msgs::Transform

### PR DESCRIPTION
**Pull request by k-okada**
This is very surprising but `ros::tf-transform->corods` does not work if we take `geometry_msg::Transform` as an argument.
The code was committed 8 years ago and seems no one have ever used before...
https://github.com/jsk-ros-pkg/jsk_roseus/commit/589e86778b9a3096ce8504fec557d3e9dba39add

### CODE REVIEW

**Comment by knorth55** [comment]
In APC, we dont use this function but we use this code for getting coordinates.
https://github.com/start-jsk/jsk_apc/blob/master/jsk_arc2017_baxter/euslisp/lib/baxter-interface.l#458-462

**Comment by k-okada** [comment]
`ros::tf-pose->coords pose` is ok, the problem is
`ros::tf-transform->corods` with `geometry_msgs/Transform`

--
◉ Kei Okada


2018-07-05 20:58 GMT+09:00 Shingo Kitagawa <notifications@github.com>:

**Comment by k-okada** [comment]
@iory @furushchev , the commit https://github.com/jsk-ros-pkg/jsk_roseus/pull/563/commits/ac12c80ebce888432bbd42b8bcfb85e46e5327d8 failing only for indigo and that was fixed if we revert https://github.com/jsk-ros-pkg/jsk_roseus/pull/557. @furushchev commented `I already more than 4 months use roseus with this fix and never met any problem`, but which ros-distro are you using. Kinetic or Indigo? 

The error seems typical case of when we forget to add `mutex_lock` or `vpush`
https://api.travis-ci.org/v3/job/400669292/log.txt
https://api.travis-ci.org/v3/job/400669290/log.txt
```
roseus [33m;; loading roseus("1.6.3-60-g57a9f17") on euslisp((9.23 ip-172-31-23-158 Mon Mar 13 06:38:31 PDT 2017  1.1.0))

[0meustf roseus_c_util roseus_c_util roseus_c_util [33moutput to /home/travis/.ros/test_results/roseus_smach/rosunit-test_async_join_state_machine_sample.xml

[0m[32mstart testing [test-async-join-state-machine]

[0mgenerated random 10

multiple transitions t from #<state #X62c2fb0 :make-random-int>

[32mwaiting action client: (#<ros::simple-action-client #X6d1b090 sub5> #<ros::simple-action-client #X6d10f00 multiply10>)

[0mCall Stack (max depth: 20):

  0: at (ros::spin-once)

  1: at (ros::spin-once)

  2: at (cond (ros::groupname (ros::spin-once ros::groupname)) (t (ros::spin-once)))

  3: at (send self :spin-once)

  4: at (while (ros::ok) (ros::ros-debug "[~A] :wait-for-result ~A ~A" ros::name-space (ros::simple-goal-states-to-string ros::simple-state) (send ros::comm-state :state)) (send self :spin-once) (if (= ros::simple-state ros::*simple-goal-state-done*) (return)) (if (> ros::timeout 0) (let* ((ros::tm (ros::time- (ros::time-now) ros::start))) (if (> (send ros::tm :to-sec) ros::timeout) (return-from :wait-for-result nil)))) (when ros::return-if-server-down (when (= (ros::get-num-publishers ros::result-topic) 0) (ros::ros-error "[~A] Unexpected returns from :wait-for-result : no publishers found for ~A" ros::name-space ros::result-topic) (return-from :wait-for-result nil)) (when (and ros::status-stamp ros::maximum-status-interval (> (send (ros::time- (ros::time-now) ros::status-stamp) :to-sec) ros::maximum-status-interval)) (ros::ros-error "[~A] Unexpected returns from :wait-for-result : status did not received for 5 seconds" ros::name-space) (return-from :wait-for-result nil))) (ros::sleep))

  5: at (let ((ros::start (ros::time-now)) (ros::result-topic (format nil "~A/result" ros::name-space))) (ros::ros-debug "[~A] :wait-for-result ~A, timeout=~A" ros::name-space (if ros::goal_id (send ros::goal_id :id)) ros::timeout) (unless ros::goal_id (ros::ros-error "[~A] :wait-for-result (return nil when no goal exists)" ros::name-space) (return-from :wait-for-result nil)) (ros::rate ros::wait-rate) (while (ros::ok) (ros::ros-debug "[~A] :wait-for-result ~A ~A" ros::name-space (ros::simple-goal-states-to-string ros::simple-state) (send ros::comm-state :state)) (send self :spin-once) (if (= ros::simple-state ros::*simple-goal-state-done*) (return)) (if (> ros::timeout 0) (let* ((ros::tm (ros::time- (ros::time-now) ros::start))) (if (> (send ros::tm :to-sec) ros::timeout) (return-from :wait-for-result nil)))) (when ros::return-if-server-down (when (= (ros::get-num-publishers ros::result-topic) 0) (ros::ros-error "[~A] Unexpected returns from :wait-for-result : no publishers found for ~A" ros::name-space ros::result-topic) (return-from :wait-for-result nil)) (when (and ros::status-stamp ros::maximum-status-interval (> (send (ros::time- (ros::time-now) ros::status-stamp) :to-sec) ros::maximum-status-interval)) (ros::ros-error "[~A] Unexpected returns from :wait-for-result : status did not received for 5 seconds" ros::name-space) (return-from :wait-for-result nil))) (ros::sleep)) (ros::ros-debug "[~A] :wait-for-result finished ~A" ros::name-space (ros::goal-status-to-string (send self :get-state))) (if (eq (send self :get-state) actionlib_msgs::goalstatus::*preempted*) (ros::ros-warn "[~A] :wait-for-result finished with preempted status" ros::name-space)) (eq (send self :get-state) actionlib_msgs::goalstatus::*succeeded*))

  6: at (send-all clients :wait-for-result :timeout timeout)

  7: at (send-all clients :wait-for-result :timeout timeout)

  8: at (send-all clients :wait-for-result :timeout timeout)

  9: at (member nil (send-all clients :wait-for-result :timeout timeout))

  10: at (if (member nil (send-all clients :wait-for-result :timeout timeout)) (setq ret nil) (setq ret t))

  11: at (let (start-time ret clients) (send self :remap userdata :invert nil) (setq start-time (ros::time-now)) (setq clients (cdr (assoc :async userdata))) (when (atom clients) (setq clients (list clients))) (warning-message 2 "waiting action client: ~A~%" clients) (send-all clients :spin-once) (if (member nil (send-all clients :wait-for-result :timeout timeout)) (setq ret nil) (setq ret t)) (warn "ret: ~A~%" ret) (set-alist :results (send-all clients :get-result) userdata) (warn "result: ~A~%" (send-all clients :get-result)) (send self :remap userdata :invert t) (return-from :execute ret))

  12: at (send last-state :execute userdata)

  13: at (let* ((last-state astate) (trans (send self :next-arc-list astate)) (exec-result (send last-state :execute userdata))) (ros::ros-debug "trans: ~A" trans) (setq trans (remove-if-not #'(lambda (tr) (send tr :check exec-result)) trans)) (case (length trans) (0 (error "undefined transition ~A from ~A~%" exec-result last-state)) (1 t) (t (case (length active-state) (1 (warn "multiple transitions ~A from ~A~%" exec-result last-state)) (t t)))) (when (not (eq astate last-state)) (error "active state has not changed ~A -> ~A~%" last-state astate) (return-from :execute-impl (send astate :name))) (setq next-active-state (append next-active-state (send-all trans :to))) (if (send astate :submachine) (send (send astate :submachine) :reset-state)) (push exec-result ret))

  14: at (while #:dolist1717 (setq astate (pop #:dolist1717)) (let* ((last-state astate) (trans (send self :next-arc-list astate)) (exec-result (send last-state :execute userdata))) (ros::ros-debug "trans: ~A" trans) (setq trans (remove-if-not #'(lambda (tr) (send tr :check exec-result)) trans)) (case (length trans) (0 (error "undefined transition ~A from ~A~%" exec-result last-state)) (1 t) (t (case (length active-state) (1 (warn "multiple transitions ~A from ~A~%" exec-result last-state)) (t t)))) (when (not (eq astate last-state)) (error "active state has not changed ~A -> ~A~%" last-state astate) (return-from :execute-impl (send astate :name))) (setq next-active-state (append next-active-state (send-all trans :to))) (if (send astate :submachine) (send (send astate :submachine) :reset-state)) (push exec-result ret)))

  15: at (let ((astate nil) (#:dolist1717 active-state)) nil (while #:dolist1717 (setq astate (pop #:dolist1717)) (let* ((last-state astate) (trans (send self :next-arc-list astate)) (exec-result (send last-state :execute userdata))) (ros::ros-debug "trans: ~A" trans) (setq trans (remove-if-not #'(lambda (tr) (send tr :check exec-result)) trans)) (case (length trans) (0 (error "undefined transition ~A from ~A~%" exec-result last-state)) (1 t) (t (case (length active-state) (1 (warn "multiple transitions ~A from ~A~%" exec-result last-state)) (t t)))) (when (not (eq astate last-state)) (error "active state has not changed ~A -> ~A~%" last-state astate) (return-from :execute-impl (send astate :name))) (setq next-active-state (append next-active-state (send-all trans :to))) (if (send astate :submachine) (send (send astate :submachine) :reset-state)) (push exec-result ret))) nil)

  16: at (dolist (astate active-state) (let* ((last-state astate) (trans (send self :next-arc-list astate)) (exec-result (send last-state :execute userdata))) (ros::ros-debug "trans: ~A" trans) (setq trans (remove-if-not #'(lambda (tr) (send tr :check exec-result)) trans)) (case (length trans) (0 (error "undefined transition ~A from ~A~%" exec-result last-state)) (1 t) (t (case (length active-state) (1 (warn "multiple transitions ~A from ~A~%" exec-result last-state)) (t t)))) (when (not (eq astate last-state)) (error "active state has not changed ~A -> ~A~%" last-state astate) (return-from :execute-impl (send astate :name))) (setq next-active-state (append next-active-state (send-all trans :to))) (if (send astate :submachine) (send (send astate :submachine) :reset-state)) (push exec-result ret)))

  17: at (let (ret next-active-state) (dolist (astate active-state) (let* ((last-state astate) (trans (send self :next-arc-list astate)) (exec-result (send last-state :execute userdata))) (ros::ros-debug "trans: ~A" trans) (setq trans (remove-if-not #'(lambda (tr) (send tr :check exec-result)) trans)) (case (length trans) (0 (error "undefined transition ~A from ~A~%" exec-result last-state)) (1 t) (t (case (length active-state) (1 (warn "multiple transitions ~A from ~A~%" exec-result last-state)) (t t)))) (when (not (eq astate last-state)) (error "active state has not changed ~A -> ~A~%" last-state astate) (return-from :execute-impl (send astate :name))) (setq next-active-state (append next-active-state (send-all trans :to))) (if (send astate :submachine) (send (send astate :submachine) :reset-state)) (push exec-result ret))) (setq active-state (unique next-active-state)) ret)

  18: at (send self :execute-impl args :step step)

  19: at (cond ((null step) (while (not (send self :goal-reached)) (send self :execute-impl args)) (send-all active-state :name)) (t (send self :execute-impl args :step step)))

  And more...

[1;31m/opt/ros/indigo/share/euslisp/jskeus/eus/Linux64/bin/irteusgl unittest-error: cannot find method (+ ros::ptr- 4) in (ros::spin-once), exitting...[0m

[31m[ERROR] test (ros::spin-once) failed ... (cannot find method 40).[0m
```
```
[0m[32mstart testing [test-async-join-state-machine]

[0mgenerated random 10

multiple transitions t from #<state #X5286fb0 :make-random-int>

[32mwaiting action client: (#<ros::simple-action-client #X5cdf090 sub5> #<ros::simple-action-client #X5cd4f00 multiply10>)

[0mCall Stack (max depth: 20):

  0: at (ros::spin-once)

  1: at (ros::spin-once)

  2: at (cond (ros::groupname (ros::spin-once ros::groupname)) (t (ros::spin-once)))

  3: at (send self :spin-once)

  4: at (while (ros::ok) (ros::ros-debug "[~A] :wait-for-result ~A ~A" ros::name-space (ros::simple-goal-states-to-string ros::simple-state) (send ros::comm-state :state)) (send self :spin-once) (if (= ros::simple-state ros::*simple-goal-state-done*) (return)) (if (> ros::timeout 0) (let* ((ros::tm (ros::time- (ros::time-now) ros::start))) (if (> (send ros::tm :to-sec) ros::timeout) (return-from :wait-for-result nil)))) (when ros::return-if-server-down (when (= (ros::get-num-publishers ros::result-topic) 0) (ros::ros-error "[~A] Unexpected returns from :wait-for-result : no publishers found for ~A" ros::name-space ros::result-topic) (return-from :wait-for-result nil)) (when (and ros::status-stamp ros::maximum-status-interval (> (send (ros::time- (ros::time-now) ros::status-stamp) :to-sec) ros::maximum-status-interval)) (ros::ros-error "[~A] Unexpected returns from :wait-for-result : status did not received for 5 seconds" ros::name-space) (return-from :wait-for-result nil))) (ros::sleep))

  5: at (let ((ros::start (ros::time-now)) (ros::result-topic (format nil "~A/result" ros::name-space))) (ros::ros-debug "[~A] :wait-for-result ~A, timeout=~A" ros::name-space (if ros::goal_id (send ros::goal_id :id)) ros::timeout) (unless ros::goal_id (ros::ros-error "[~A] :wait-for-result (return nil when no goal exists)" ros::name-space) (return-from :wait-for-result nil)) (ros::rate ros::wait-rate) (while (ros::ok) (ros::ros-debug "[~A] :wait-for-result ~A ~A" ros::name-space (ros::simple-goal-states-to-string ros::simple-state) (send ros::comm-state :state)) (send self :spin-once) (if (= ros::simple-state ros::*simple-goal-state-done*) (return)) (if (> ros::timeout 0) (let* ((ros::tm (ros::time- (ros::time-now) ros::start))) (if (> (send ros::tm :to-sec) ros::timeout) (return-from :wait-for-result nil)))) (when ros::return-if-server-down (when (= (ros::get-num-publishers ros::result-topic) 0) (ros::ros-error "[~A] Unexpected returns from :wait-for-result : no publishers found for ~A" ros::name-space ros::result-topic) (return-from :wait-for-result nil)) (when (and ros::status-stamp ros::maximum-status-interval (> (send (ros::time- (ros::time-now) ros::status-stamp) :to-sec) ros::maximum-status-interval)) (ros::ros-error "[~A] Unexpected returns from :wait-for-result : status did not received for 5 seconds" ros::name-space) (return-from :wait-for-result nil))) (ros::sleep)) (ros::ros-debug "[~A] :wait-for-result finished ~A" ros::name-space (ros::goal-status-to-string (send self :get-state))) (if (eq (send self :get-state) actionlib_msgs::goalstatus::*preempted*) (ros::ros-warn "[~A] :wait-for-result finished with preempted status" ros::name-space)) (eq (send self :get-state) actionlib_msgs::goalstatus::*succeeded*))

  6: at (send-all clients :wait-for-result :timeout timeout)

  7: at (send-all clients :wait-for-result :timeout timeout)

  8: at (send-all clients :wait-for-result :timeout timeout)

  9: at (member nil (send-all clients :wait-for-result :timeout timeout))

  10: at (if (member nil (send-all clients :wait-for-result :timeout timeout)) (setq ret nil) (setq ret t))

  11: at (let (start-time ret clients) (send self :remap userdata :invert nil) (setq start-time (ros::time-now)) (setq clients (cdr (assoc :async userdata))) (when (atom clients) (setq clients (list clients))) (warning-message 2 "waiting action client: ~A~%" clients) (send-all clients :spin-once) (if (member nil (send-all clients :wait-for-result :timeout timeout)) (setq ret nil) (setq ret t)) (warn "ret: ~A~%" ret) (set-alist :results (send-all clients :get-result) userdata) (warn "result: ~A~%" (send-all clients :get-result)) (send self :remap userdata :invert t) (return-from :execute ret))

  12: at (send last-state :execute userdata)

  13: at (let* ((last-state astate) (trans (send self :next-arc-list astate)) (exec-result (send last-state :execute userdata))) (ros::ros-debug "trans: ~A" trans) (setq trans (remove-if-not #'(lambda (tr) (send tr :check exec-result)) trans)) (case (length trans) (0 (error "undefined transition ~A from ~A~%" exec-result last-state)) (1 t) (t (case (length active-state) (1 (warn "multiple transitions ~A from ~A~%" exec-result last-state)) (t t)))) (when (not (eq astate last-state)) (error "active state has not changed ~A -> ~A~%" last-state astate) (return-from :execute-impl (send astate :name))) (setq next-active-state (append next-active-state (send-all trans :to))) (if (send astate :submachine) (send (send astate :submachine) :reset-state)) (push exec-result ret))

  14: at (while #:dolist1732 (setq astate (pop #:dolist1732)) (let* ((last-state astate) (trans (send self :next-arc-list astate)) (exec-result (send last-state :execute userdata))) (ros::ros-debug "trans: ~A" trans) (setq trans (remove-if-not #'(lambda (tr) (send tr :check exec-result)) trans)) (case (length trans) (0 (error "undefined transition ~A from ~A~%" exec-result last-state)) (1 t) (t (case (length active-state) (1 (warn "multiple transitions ~A from ~A~%" exec-result last-state)) (t t)))) (when (not (eq astate last-state)) (error "active state has not changed ~A -> ~A~%" last-state astate) (return-from :execute-impl (send astate :name))) (setq next-active-state (append next-active-state (send-all trans :to))) (if (send astate :submachine) (send (send astate :submachine) :reset-state)) (push exec-result ret)))

  15: at (let ((astate nil) (#:dolist1732 active-state)) nil (while #:dolist1732 (setq astate (pop #:dolist1732)) (let* ((last-state astate) (trans (send self :next-arc-list astate)) (exec-result (send last-state :execute userdata))) (ros::ros-debug "trans: ~A" trans) (setq trans (remove-if-not #'(lambda (tr) (send tr :check exec-result)) trans)) (case (length trans) (0 (error "undefined transition ~A from ~A~%" exec-result last-state)) (1 t) (t (case (length active-state) (1 (warn "multiple transitions ~A from ~A~%" exec-result last-state)) (t t)))) (when (not (eq astate last-state)) (error "active state has not changed ~A -> ~A~%" last-state astate) (return-from :execute-impl (send astate :name))) (setq next-active-state (append next-active-state (send-all trans :to))) (if (send astate :submachine) (send (send astate :submachine) :reset-state)) (push exec-result ret))) nil)

  16: at (dolist (astate active-state) (let* ((last-state astate) (trans (send self :next-arc-list astate)) (exec-result (send last-state :execute userdata))) (ros::ros-debug "trans: ~A" trans) (setq trans (remove-if-not #'(lambda (tr) (send tr :check exec-result)) trans)) (case (length trans) (0 (error "undefined transition ~A from ~A~%" exec-result last-state)) (1 t) (t (case (length active-state) (1 (warn "multiple transitions ~A from ~A~%" exec-result last-state)) (t t)))) (when (not (eq astate last-state)) (error "active state has not changed ~A -> ~A~%" last-state astate) (return-from :execute-impl (send astate :name))) (setq next-active-state (append next-active-state (send-all trans :to))) (if (send astate :submachine) (send (send astate :submachine) :reset-state)) (push exec-result ret)))

  17: at (let (ret next-active-state) (dolist (astate active-state) (let* ((last-state astate) (trans (send self :next-arc-list astate)) (exec-result (send last-state :execute userdata))) (ros::ros-debug "trans: ~A" trans) (setq trans (remove-if-not #'(lambda (tr) (send tr :check exec-result)) trans)) (case (length trans) (0 (error "undefined transition ~A from ~A~%" exec-result last-state)) (1 t) (t (case (length active-state) (1 (warn "multiple transitions ~A from ~A~%" exec-result last-state)) (t t)))) (when (not (eq astate last-state)) (error "active state has not changed ~A -> ~A~%" last-state astate) (return-from :execute-impl (send astate :name))) (setq next-active-state (append next-active-state (send-all trans :to))) (if (send astate :submachine) (send (send astate :submachine) :reset-state)) (push exec-result ret))) (setq active-state (unique next-active-state)) ret)

  18: at (send self :execute-impl args :step step)

  19: at (cond ((null step) (while (not (send self :goal-reached)) (send self :execute-impl args)) (send-all active-state :name)) (t (send self :execute-impl args :step step)))

  And more...

[1;31m/opt/ros/indigo/share/euslisp/jskeus/eus/Linux64/bin/irteusgl unittest-error: cannot find method ros::cnsec in (ros::spin-once), exitting...[0m

[31m[ERROR] test (ros::spin-once) failed ... (cannot find method 40).[0m

testtest_async_join_state_machine_sample ... ok



[ROSTEST]-----------------------------------------------------------------------



[roseus_smach.rosunit-test_async_join_state_machine_sample/all-test][FAILURE]---

Test:(ros::spin-once)

Trace:40

Message:"cannot find method"
```

**Comment by k-okada** [comment]
humm, restart travis on July 7th fixed problem...

**Comment by furushchev** [comment]
oh, I use the branch on kinetic.

**Comment by k-okada** [comment]
restarting travis on July 8 fails and july 11 passed....

**Pull request merged**
