### PR TITLE
[roseus_mongo] add mongo client for roseus

### PR DESCRIPTION
**Pull request by furushchev**

### CODE REVIEW

**Comment by k-okada** [comment]
ping

**Comment by furushchev** [comment]
@k-okada hi!

**Comment by furushchev** [comment]
@k-okada travis failed because I forgot to update test code against code changes. I updated test codes, sorry.

**Comment by furushchev** [comment]
@k-okada travis failed because maybe no apt version of mongodb_store? What should I do in order to use source version only on jade env?

**Comment by k-okada** [comment]
ok, asked for release, if they're not, check ROS_DISTRO and skip compile.

--
◉ Kei Okada

**Comment by furushchev** [comment]
@k-okada Thank you very much!

**Comment by furushchev** [comment]
travis failed regardless of appending script to ignore roseus_mongo compilation on jade. weird...

**Comment by k-okada** [comment]
this is because BEFORE_SCRIPT is not passed to jenkins server, I'm working on that at https://github.com/jsk-ros-pkg/jsk_travis/pull/111

but this fix only effective on travis test, my suggestion is check ROS_DISTRO within cmake and skip compile, for example put
```
if ("$ENV{ROS_DISTRO}" STREQUAL "jade")
  return()
endif()
```
on the top of CMakeLists.txt

https://github.com/jsk-ros-pkg/jsk_3rdparty/blob/master/jsk_ros_patch/collada_urdf_jsk_patch/CMakeLists.txt#L7

**Comment by furushchev** [comment]
@k-okada I added to CMakeLists.txt

```cmake
if ("$ENV{ROS_DISTRO}" STREQUAL "jade")
  return()
endif()
```

but with it yet executes `catkin run_tests`, which fails.
How can I exclude this pkg from env `TEST_PKGS`?

**Comment by k-okada** [comment]
manually specify TEST_PKGS in .travis.yaml

**Comment by furushchev** [comment]
build on hydro USE_DEB=true failed because of non-related error?

```
Full test results for 'tf2_ros/rosunit-transform_listener_time_reset_test.xml'
-------------------------------------------------
<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="1" failures="1" disabled="0" errors="0" time="2.296" name="AllTests">
  <testsuite name="tf2_ros_transform_listener" tests="1" failures="1" disabled="0" errors="0" time="2.296">
    <testcase name="time_backwards" status="run" time="2.296" classname="tf2_ros_transform_listener">
      <failure message="Value of: buffer.canTransform(&quot;foo&quot;, &quot;bar&quot;, ros::Time(101, 0))&#x0A;  Actual: true&#x0A;Expected: false" type=""><![CDATA[/home/travis/ros/ws_jsk_roseus/src/geometry-experimental/tf2_ros/test/time_reset_test.cpp:79
Value of: buffer.canTransform("foo", "bar", ros::Time(101, 0))
  Actual: true
Expected: false]]></failure>
    </testcase>
  </testsuite>
</testsuites>

-------------------------------------------------
Skipping "tf2_ros/rostest-test_transform_listener_time_reset_test.xml": not well-formed (invalid token): line 5, column 0
roseus/rostest-test_test-actionlib.xml: 0 tests
roseus/rosunit-add_two_ints.xml: 2 tests
roseus/rosunit-eus_disconnect.xml: 1 tests
roseus/rosunit-eusroseus.xml: 3 tests
roseus/rosunit-eustf.xml: 8 tests
roseus/rosunit-multi_queue.xml: 1 tests
roseus/rosunit-read_parameter.xml: 2 tests
roseus/rosunit-simple_client_test.xml: 1 tests
roseus/rosunit-simple_client_wait_test.xml: 1 tests
roseus/rosunit-talker_listener_test.xml: 1 tests
roseus/rosunit-test_anonymous.xml: 1 tests
roseus/rosunit-test_geneus.xml: 2 tests
roseus/rosunit-test_geneus_dep1.xml: 1 tests
roseus/rosunit-test_geneus_remove_msg.xml: 1 tests
roseus/rosunit-test_genmsg.xml: 1 tests
roseus_mongo/rosunit-test_json_decode.xml: 8 tests
roseus_mongo/rosunit-test_json_encode.xml: 2 tests
roseus_mongo/rosunit-test_mongo_client.xml: 1 tests
roseus_smach/rosunit-test_async_join_state_machine_sample.xml: 1 tests
roseus_smach/rosunit-test_roseus_smach_samples.xml: 3 tests
tf/rosunit-test_broadcaster_reciept.xml: 2 tests
tf/rosunit-test_message_filter.xml: 11 tests
tf/rosunit-transform_listener_unittest.xml: 1 tests
tf2_ros/rosunit-transform_listener_time_reset_test.xml: 1 tests, 0 errors, 1 failures
tf2_ros/rosunit-transform_listener_unittest.xml: 1 tests
Summary: 57 tests, 0 errors, 1 failures
```

**Comment by k-okada** [comment]
tf2_ros test sometimes fail, restarted travis

--
◉ Kei Okada

**Comment by furushchev** [comment]
@k-okada Thanks for merging!

**Pull request merged**
