### PR TITLE
[generate-all-msg-srv.sh] write list of packages ONLY contains msg/srv/a...

### PR DESCRIPTION
**Pull request by k-okada**
...ction

for #239

### CODE REVIEW

**Comment by k-okada** [comment]
this will generate
```
;;
;; DO NOT EDIT THIS FILE
;;
(ros::load-ros-package "std_msgs")
(ros::load-ros-package "rosgraph_msgs")
(ros::load-ros-package "roscpp")
(ros::load-ros-package "topic_tools")
(ros::load-ros-package "actionlib_msgs")
(ros::load-ros-package "actionlib")
(ros::load-ros-package "geometry_msgs")
(ros::load-ros-package "visualization_msgs")
(ros::load-ros-package "sensor_msgs")
(ros::load-ros-package "tf2_msgs")
(ros::load-ros-package "tf")
(ros::load-ros-package "std_srvs")
(ros::load-ros-package "dynamic_reconfigure")
(ros::load-ros-package "roseus")
```
for roseus, please confirm if this is identical to geneus version @furushchev

**Comment by furushchev** [comment]
As I see `$HOME/.ros/roseus/roseus/manifest.l`(that was generated by geneus euslisp version),
it's ok.

```lisp
;;
;; DO NOT EDIT THIS FILE
;;
;; Auto-generated from roseus
;;  at Thu Jun 20 21:48:56 2013
;;  using EusLisp 8.26(r644M) for Linux64 created on pr1040(Wed Jun 5 03:42:33 PDT 2013)
;;

(ros::load-ros-package "catkin")
(ros::load-ros-package "genmsg")
(ros::load-ros-package "roslang")
(ros::load-ros-package "cpp_common")
(ros::load-ros-package "rostime")
(ros::load-ros-package "roscpp_traits")
(ros::load-ros-package "roscpp_serialization")
(ros::load-ros-package "genpy")
(ros::load-ros-package "message_runtime")
(ros::load-ros-package "rosconsole")
(ros::load-ros-package "std_msgs")
(ros::load-ros-package "rosgraph_msgs")
(ros::load-ros-package "xmlrpcpp")
(ros::load-ros-package "roscpp")
(ros::load-ros-package "rospack")
(ros::load-ros-package "euslisp")
(ros::load-ros-package "gencpp")
(ros::load-ros-package "genlisp")
(ros::load-ros-package "message_generation")
(ros::load-ros-package "actionlib_msgs")
(ros::load-ros-package "rosgraph")
(ros::load-ros-package "roslib")
(ros::load-ros-package "rospy")
(ros::load-ros-package "rosclean")
(ros::load-ros-package "rosmaster")
(ros::load-ros-package "rosout")
(ros::load-ros-package "rosparam")
(ros::load-ros-package "roslaunch")
(ros::load-ros-package "rosunit")
(ros::load-ros-package "rostest")
(ros::load-ros-package "actionlib")
(ros::load-ros-package "geometry_msgs")
(ros::load-ros-package "visualization_msgs")
(ros::load-ros-package "message_filters")
(ros::load-ros-package "sensor_msgs")
(ros::load-ros-package "tf")
(ros::load-ros-package "tf2_msgs")
(ros::load-ros-package "tf2")
(ros::load-ros-package "tf2_ros")
(ros::load-ros-package "std_srvs")
(ros::load-ros-package "actionlib_tutorials")
(ros::load-ros-package "roseus")
```

comparing to manifest.l generated by python-version geneus:

```lisp
;;
;; DO NOT EDIT THIS FILE
;;
(ros::load-ros-package "geometry_msgs")
(ros::load-ros-package "std_msgs")
(ros::load-ros-package "roseus")
```

**Comment by furushchev** [comment]
I think it's ok to merge. :+1:

**Comment by k-okada** [comment]
No, the test is not running as we expected

Please wait

2015年2月20日金曜日、Furushchev<notifications@github.com>さんは書きました:

> I think it's ok to merge. [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_roseus/pull/240#issuecomment-75229584>
> .
>


-- 
--
◉ Kei Okada

**Comment by k-okada** [comment]
this issue is working on #249

**Pull request closed without merging**
