### PR TITLE
[roseus/roseus.cpp] fix: segfault when no response is returned on service callback

### PR DESCRIPTION
**Pull request by furushchev**
related to https://github.com/euslisp/EusLisp/pull/206
this pull request will solve https://github.com/jsk-ros-pkg/jsk_roseus/issues/417

### CODE REVIEW

**Comment by k-okada** [comment]
can we create test code for this feature?

**Comment by furushchev** [comment]
@k-okada Sure, of course. But I'm not sure how I catch error on eus `C` level.

for example:

```lisp
;;; test-error.l
(print not-bound)
```

```lisp
$ irteusgl test-error.l
;; omit header
ERROR th=0 unbound variable not-boundnot-bound in (print not-bound)E:
```

**Comment by k-okada** [comment]
````
k-okada@p40-yoga:/tmp$ cat hoge.l 
(require :unittest "lib/llib/unittest.l")
(init-unit-test)
(print not-bound)
k-okada@p40-yoga:/tmp$ irteusgl hoge.l
configuring by "/opt/ros/indigo/share/euslisp/jskeus/eus//lib/eusrt.l"
;; readmacro ;; object ;; packsym ;; common ;; constants ;; stream ;; string ;; loader ;; pprint ;; process ;; hashtab ;; array ;; mathtran ;; eusdebug ;; eusforeign ;; coordinates ;; tty ;; history ;; toplevel ;; trans ;; comp ;; builtins ;; par ;; intersection ;; geoclasses ;; geopack ;; geobody ;; primt ;; compose ;; polygon ;; viewing ;; viewport ;; viewsurface ;; hid ;; shadow ;; bodyrel ;; dda ;; helpsub ;; eushelp ;; xforeign ;; Xdecl ;; Xgraphics ;; Xcolor ;; Xeus ;; Xevent ;; Xpanel ;; Xitem ;; Xtext ;; Xmenu ;; Xscroll ;; Xcanvas ;; Xtop ;; Xapplwin 
connected to Xserver DISPLAY=:0
X events are being asynchronously monitored.
;; pixword ;; RGBHLS ;; convolve ;; piximage ;; pbmfile ;; image_correlation ;; oglforeign ;; gldecl ;; glconst ;; glforeign ;; gluconst ;; gluforeign ;; glxconst ;; glxforeign ;; eglforeign ;; eglfunc ;; glutil ;; gltexture ;; glprim ;; gleus ;; glview ;; toiv-undefined ;; fstringdouble irtmath irtutil irtc irtgeoc irtgraph pgsql irtgeo euspqp pqp irtscene irtmodel irtdyna irtrobot irtsensor irtbvh irtcollada irtpointcloud irtx eusjpeg euspng png irtimage irtglrgb 
;; extending gcstack 0x523dde0[16374] --> 0x569a120[32748] top=3cc1
irtgl irtglc irtviewer 
EusLisp 9.21( 1.0.13) for Linux64 created on ip-172-31-6-90(Mon Sep 5 10:32:52 PDT 2016)
irteusgl unittest-error: unbound variable not-bound in (print not-bound), exitting...
[ERROR] test (print not-bound) failed ... (unbound variable 12).
ALL RESULTS:
  TEST-NUM: 0
    PASSED:   0
    FAILURE:  0
```
how about this?

**Comment by furushchev** [comment]
@k-okada Added test code. Thanks to test code, I caught two additional potential bugs.

**Pull request merged**
