### PR TITLE
[roseus] Fix generating Euslisp ROS message with catkin_tools 0.4.x

### PR DESCRIPTION
**Pull request by wkentaro**
@k-okada This fixes my problem I reported you before.

Modified:
  - roseus/cmake/roseus.cmake

### CODE REVIEW

**Comment by k-okada** [comment]
This will solve  https://github.com/jsk-ros-pkg/geneus/issues/47

**Comment by k-okada** [comment]
maybe we need to update jsk_travis, move to #422

**Comment by wkentaro** [comment]
```
+[[ -n '' ]]
+eval 'rostest -t roseus test-genmsg.catkin.test'
++rostest -t roseus test-genmsg.catkin.test
/home/travis/build.sh: line 45: rostest: command not found
```

**Comment by k-okada** [comment]
moved to #447

**Pull request closed without merging**
