### PR TITLE
[roseus] remove error message meanless in get-topic-publisher

### PR DESCRIPTION
**Pull request by aginika**
This function is used in speak.l and is used to check whether is there any publisher or not.
When the publisher is none, this shouldn't be the error, so I deleted this noisy message.

### CODE REVIEW

**Comment by k-okada** [comment]
> When the publisher is none, this shouldn't be the error, 

where did you find this definition?

**Comment by aginika** [comment]
There is not a such definition.
But this function is just to check whether the passed topic name is existed or not.

```
map<string, boost::shared_ptr<Publisher> >::iterator it = s_mapAdvertised.find(topicname);
  if( it != s_mapAdvertised.end() ) {
    boost::shared_ptr<Publisher> publisher = (it->second);
    ret = publisher->getTopic();
    bSuccess = true;
  }
```

The error appearence should be deligated to user 

This functions are only used in below files and is used for checking whether advertise is needed or not.
```
jsk_robot/jsk_robot_common/jsk_robot_startup/lifelog/tweet_client.l
jsk_pr2eus/pr2eus/speak.l
```

But anyway I will close this.

**Comment by k-okada** [comment]
how about using ROS_WARN?

--
◉ Kei Okada

**Comment by aginika** [comment]
that would be better. 
I will update again.

**Comment by garaemon** [comment]
I prefer @aginika 's original proposal because whether it should be an error or warning depends on application side.

**Comment by k-okada** [comment]
I finally understand original @aginika 's PR, yes, you're correct, and isAdviertised proposed in 306 is equal to get-topic-publisher, please reopen this, and please also remove error message from get-topic-subscriber, too

I'm not sure why did I introduce this function at this moment -> 
https://github.com/jsk-ros-pkg/jsk_roseus/commit/858d11f10d3107c522fef72be32471322832b8d4

**Comment by k-okada** [comment]
please fix get-topic-subscriber too

--
◉ Kei Okada

**Comment by wkentaro** [comment]
Should I check if there is the subscriber using `get-topic-subscriber` when subscriptions as well as publications?

**Comment by k-okada** [comment]
may be no

--
◉ Kei Okada

**Comment by aginika** [comment]
I updated

**Comment by k-okada** [comment]
Thx

**Pull request merged**
