### PR TITLE
modify make-state-machine

### PR DESCRIPTION
**Pull request by h-kamada**
#### modified make-state-machine function
By parameter state-machine,  state-machine is set nil.

### CODE REVIEW

**Comment by furushchev** [comment]
@h-kamada Thanks a lot! This is just a bug!

**Comment by k-okada** [comment]
travis did not start, not sure why

**Comment by k-okada** [comment]
could you use `git rebase -i HEAD~1` and use `r` to fix log, and amend commit

**Comment by h-kamada** [comment]
what's r to fix log??


2015-04-24 18:48 GMT+09:00 Kei Okada <notifications@github.com>:

**Comment by garaemon** [comment]
recently travis has not reported test status in many repositories

2015年4月24日金曜日、h-kamada<notifications@github.com>さんは書きました:

> what's r to fix log??
>
>
> 2015-04-24 18:48 GMT+09:00 Kei Okada <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>:
>
> > could you use git rebase -i HEAD~1 and use r to fix log, and amend commit
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/jsk-ros-pkg/jsk_roseus/pull/282#issuecomment-95875815>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_roseus/pull/282#issuecomment-95898149>
> .
>


-- 
✉︎ from iPhone

**Comment by h-kamada** [comment]
I rewarded commit message.

**Comment by k-okada** [comment]
test status did not show, but it passed https://travis-ci.org/jsk-ros-pkg/jsk_roseus/builds/59970083,

in next time, please create PR after creating branch, not from your master branch. Also please update your profile photo > @h-kamada

**Pull request merged**
