### PR TITLE
[roseus] Warn about wait time in one-shot-publish

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by wkentaro** [comment]
If there is no time between constructing publisher and publishing, program does not work and there is no published message.

**Comment by k-okada** [comment]
please re-open if you still need this, and not clear why you wave to wait 1.5 sec, not 1.0 nor 2.0.

**Comment by wkentaro** [comment]
*I* don't need this because I know this function is dangerous to use to publish a message. The warning is for other possible users of this function.

**Comment by wkentaro** [comment]
The reason why I selected 1.5 seconds is that is nearest to the border b/w work and does not wor, I thought. 
If I chage it to 2.0 sec, can this be merged?

**Pull request closed without merging**
