### PR TITLE
[roseus_smach] add failure nodes addition feature for state-machine generation utils

### PR DESCRIPTION
**Pull request by furushchev**
assumed merging after #376

### CODE REVIEW

**Comment by furushchev** [comment]
travis failed:

```
[0m;; Segmentation Fault.
*** glibc detected *** /home/travis/ros/ws_jsk_roseus/install/share/euslisp/jskeus/eus/Linux64/bin/irteusgl: corrupted double-linked list: 0x00000000061bde50 ***
testtest_parallel_state_machine_samples ... ERROR!
ERROR: test max time allotted
  File "/usr/lib/python2.7/unittest/case.py", line 327, in run
    testMethod()
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rostest/runner.py", line 146, in fn
    self.test_parent.run_test(test)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rostest/rostest_parent.py", line 91, in run_test
    return self.runner.run_test(test)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/launch.py", line 669, in run_test
    raise RLTestTimeoutException("test max time allotted")
```

**Comment by k-okada** [comment]
did you confirm that your test finished within `time-limit` ?
http://answers.ros.org/question/10902/change-rostest-max-time-allotted/

--
◉ Kei Okada

**Comment by furushchev** [comment]
@k-okada Thank you for advice. I checked and now it passed on all hydro and indigo.
on jade, test on jenkins seems to be aborted. Do you know the behavior? or what to do?

```bash
Build was aborted
Aborted by anonymous
Finished: ABORTED
```

**Comment by k-okada** [comment]
because of rebooting jenkins server? restarted travis

--
◉ Kei Okada

**Comment by furushchev** [comment]
@k-okada Thank you!

**Comment by furushchev** [comment]
> from #376
>  This may make conflict when merging #377

now resolved conflict. please merge if no problem

**Pull request merged**
