### PR TITLE
[.travis.yml] allow failure on hydro && USE_DEB=true because of EOL

### PR DESCRIPTION
**Pull request by furushchev**

### CODE REVIEW

**Comment by furushchev** [comment]
travis passed. please merge if no problem.

**Comment by furushchev** [comment]
> is it right way to disable test of hydro && USE_DEB=true?

Confirmed with @k-okada on offline.
Please merge if there is no problem.

**Comment by k-okada** [comment]
I'd like merge this one if we have no any other  way to disable test, at this momemt, I think we can use this (
https://github.com/jsk-ros-pkg/jsk_roseus/pull/382#issuecomment-152982848) strategy.

**Comment by furushchev** [comment]
closed since https://github.com/jsk-ros-pkg/jsk_roseus/pull/382 was merged.

**Pull request closed without merging**
