### PR TITLE
[roseus_smach/src/state-machine.l] another impl for #383

### PR DESCRIPTION
**Pull request by furushchev**
https://github.com/jsk-ros-pkg/jsk_roseus/pull/383#issuecomment-153257520

### CODE REVIEW

**Comment by furushchev** [comment]
how should i do...XP

**Comment by k-okada** [comment]
xp ? xor ? extreme programming?

--
◉ Kei Okada

**Comment by furushchev** [comment]
Sorry I assume it is a kind of emoji...

**Comment by k-okada** [comment]
i see, how do you think @h-kamada

--
◉ Kei Okada

**Comment by h-kamada** [comment]
I think frushchev's verstion is better!

**Pull request merged**
