### PR TITLE
update jsk_travis to 0.5.21

### PR DESCRIPTION
**Pull request by knorth55**
update jsk_travis to 0.5.21

### CODE REVIEW

**Comment by knorth55** [comment]
test fails because of https://github.com/jsk-ros-pkg/jsk_travis/issues/423

**Comment by knorth55** [comment]
I update this PR to 0.5.21

**Comment by Affonso-Gui** [comment]
Any updates in this one?

**Comment by k-okada** [comment]
restarted travis
--
◉ Kei Okada



2021年8月12日(木) 16:08 Affonso, Guilherme ***@***.***>:

**Pull request closed without merging**
