### PR TITLE
[roseus_smach] fix file name typo; add test for parallel state machine

### PR DESCRIPTION
**Pull request by furushchev**

### CODE REVIEW

**Comment by furushchev** [comment]
travis failed because of using not-yet-generated geneus messages

```
EusLisp 9.12( 1.0.6) for Linux64 created on host04.storm.ros.org(Thu Apr 23 17:08:16 UTC 2015)[0m

roseus [33m;; loading roseus("968dd22") on euslisp((9.12 host04.storm.ros.org Thu Apr 23 17:08:16 UTC 2015  1.0.6))

[0meustf roseus_c_util [31m[ERROR] [1430330886.627454868]: Could not find roseus messages for smach_msgs under (/home/travis/ros/ws_jsk_roseus/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)

try rosrun roseus generate-all-msg-srv.sh smach_msgs[0m

[31m;; can not find nil/msg/ directory for [smach_msgs] packages

[0mtesttest_parallel_smach_samples ... FAILURE!

FAILURE: test [test_parallel_smach_samples] did not generate test results

  File "/usr/lib/python2.7/unittest/case.py", line 327, in run

    testMethod()

  File "/opt/ros/hydro/lib/python2.7/dist-packages/rostest/runner.py", line 162, in fn

    self.assert_(os.path.isfile(test_file), "test [%s] did not generate test results"%test_name)

  File "/usr/lib/python2.7/unittest/case.py", line 420, in assertTrue

    raise self.failureException(msg)

--------------------------------------------------------------------------------



[ROSTEST]-----------------------------------------------------------------------



[testtest_parallel_smach_samples][failed]
```

**summary**:
`try rosrun roseus generate-all-msg-srv.sh smach_msgs`

how can I generate non source package automatically?

The order of roseus in `find_package` is still severe?

```
+find_package(catkin REQUIRED COMPONENTS
+  euslisp
+  rostest
+  roseus
+  smach
+  smach_ros
+  smach_msgs)
```

**Comment by k-okada** [comment]
you need to put rosues at the end of find_package

**Comment by k-okada** [comment]
you still have wrong .travis here,

**Comment by furushchev** [comment]
Thanks to you, travis passed. Please merge!

**Comment by k-okada** [comment]
merging another PR breaks this one, I would recommend you to organize PR, for example 1 is for new feature, 1 is update travsi (if needed, at this moment you do not need), 1 is for change code style,,,, etc.

**Comment by furushchev** [comment]
All commits of this PR are opened as new small PRs.

**Pull request closed without merging**
