### PR TITLE
add test code for marker/eus conversion

### PR DESCRIPTION
**Pull request by k-okada**
@aginika please merge this one before your https://github.com/jsk-ros-pkg/jsk_roseus/pull/327 commit, and confirm this PR fails and fixed by your PR
- [test/test-roseus.l] add test code for marker message <-> eus object conversion function in euslisp/roseus-utils.l

### CODE REVIEW

**Comment by aginika** [comment]
@k-okada 
I confirmed that , without my PR, I got error with 
```
/opt/ros/hydro/share/euslisp/jskeus/eus/Linux64/bin/irteusgl unittest-error: cannot find method :body-type in (send body :body-type), exitting...
[ERROR] test (send body :body-type) failed ... (cannot find method 40).
```

and 
with my PR, the error didn't appear.

**Comment by k-okada** [comment]
oh, I mean please create PR that  include test code and fixed code, like this one.

**Comment by aginika** [comment]
@k-okada Sorry for that.
So I don't need to create PR anymore?

**Comment by k-okada** [comment]
everything ok now.

**Pull request merged**
