### PR TITLE
[roseus_mongo] add limit option for query

### PR DESCRIPTION
**Pull request by furushchev**
Test should fail
waiting for https://github.com/strands-project/mongodb_store/pull/147

### CODE REVIEW

**Comment by furushchev** [comment]
fix on upstream was merged.
restarted travis

**Comment by furushchev** [comment]
failed again
- disable hydro + deb test https://github.com/jsk-ros-pkg/jsk_travis/pull/180
- bug on travis use_deb=source https://github.com/jsk-ros-pkg/jsk_travis/pull/180 -> need to update `.travis`

**Comment by k-okada** [comment]
```
$ (car (last lisp-implementation-version))
"1.0.11"
$ unix::getenv "ROS_DISTRO"
"indigo"

```
can you disable test which is not supported on hydro anymore?
you can use jskeus version or rosdistro

**Comment by furushchev** [comment]
@k-okada OK. I limited test for indigo and later only.

**Comment by k-okada** [comment]
do you think we can revert .travis.rosinstall, because it seems newer version of mongo_store is already released
http://www.ros.org/debbuild/indigo.html?q=mongo

**Pull request merged**
