### PR TITLE
[roseus_mongo] support timezone

### PR DESCRIPTION
**Pull request by furushchev**
mongodb uses utc time at internal bson schema.
test should be passed after merging https://github.com/euslisp/EusLisp/pull/128

### CODE REVIEW

**Comment by k-okada** [comment]
please remove .travis from your commit

**Comment by furushchev** [comment]
@k-okada Sorry, reverted .travis.

**Comment by k-okada** [comment]
I think we have to wait until next deb release

--
◉ Kei Okada

**Comment by garaemon** [comment]
merge origin/master

**Comment by garaemon** [comment]
mongodb test?
```
]2;[build] 1/4[0m[31m[ERROR] test (and (eq (send res2 :year) 2015) (eq (send res2 :month) 7) (eq (send res2 :day) 26) (eq (send res2 :hour) 17) (eq (send res2 :minute) 48) (eq (send res2 :second) 33) (eq (send res2 :micro) 823)) failed ... ( [0mmoutput to /home/travis/.ros/test_results/roseus_mongo/rosunit-test_json_decode.xml [0m[0m
]2;[build] 1/4:16 UTC 2015  1.0.6))                                                           [0m[0m
]2;[build] 1/4).[0m                                                                              [0m[0m
]2;[build] 1/4[32mstart testing [test-skip-space]                                                 [0m[0m
]2;[build] 1/4[0m[32mstart testing [test-read-char]                                                  [0m[0m
]2;[build] 1/4[0m[32mstart testing [test-json-decode-number]                                         [0m[0m
]2;[build] 1/4[0m[32mstart testing [test-json-decode-constant]                                       [0m[0m
]2;[build] 1/4[0m[32mstart testing [test-json-decode-string]                                         [0m[0m
]2;[build] 1/4[0m[32mstart testing [test-json-decode-array]                                          [0m[0m
]2;[build] 1/4[0m[32mstart testing [test-json-decode-object]                                         [0m[0m
]2;[build] 1/4[0m[32mstart testing [test-json-decode-date]                                           [0m[0m
]2;[build] 1/4[0m[31m[ERROR] test (and (eq (send res1 :year) 2015) (eq (send res1 :month) 7) (eq (send res1 :day) 26) (eq (send res1 :hour) 8) (eq (send res1 :minute) 48) (eq (send res1 :second) 33) (eq (send res1 :micro) 823)) failed ... ( [0mmstart testing [test-json-decode-date] [0m[0m
]2;[build] 1/4]                                                                               [0m[0m
]2;[build] 1/4]                                                                               [0m[0m
]2;[build] 1/4decode.xml                                                                      [0m[0m
]2;[build] 1/4:16 UTC 2015  1.0.6))                                                           [0m[0m
]2;[build] 1/4).[0m                                                                              [0m[0m
]2;[build] 1/4iled ... ( [0mmoutput to /home/travis/.r).[0m                                         [0m[0m
]2;[build] 1/4]2;[build] 1/4]2;[build] 1/4]2;[build] 1/4]2;[build] 1/4testtest_json_decode ... ok                                                     [0m[0m
]2;[build] 1/4                                                                                [0m[0m
]2;[build] 1/4[ROSTEST]----------------------------------------------------------------------- [0m[0m
]2;[build] 1/4                                                                                [0m[0m
]2;[build] 1/4[roseus_mongo.rosunit-test_json_decode/all-test][passed]                        [0m[0m
]2;[build] 1/4[roseus_mongo.rosunit-test_json_decode/test-skip-space][passed]                 [0m[0m
]2;[build] 1/4[roseus_mongo.rosunit-test_json_decode/test-read-char][passed]                  [0m[0m
]2;[build] 1/4[roseus_mongo.rosunit-test_json_decode/test-json-decode-number][passed]         [0m[0m
]2;[build] 1/4[roseus_mongo.rosunit-test_json_decode/test-json-decode-constant][passed]       [0m[0m
]2;[build] 1/4[roseus_mongo.rosunit-test_json_decode/test-json-decode-string][passed]         [0m[0m
]2;[build] 1/4[roseus_mongo.rosunit-test_json_decode/test-json-decode-array][passed]          [0m[0m
]2;[build] 1/4[roseus_mongo.rosunit-test_json_decode/test-json-decode-object][passed]         [0m[0m
]2;[build] 1/4[roseus_mongo.rosunit-test_json_decode/test-json-decode-date][FAILURE]---------- [0m[0m
]2;[build] 1/4Test:(and (eq (send res1 :year) 2015) (eq (send res1 :month) 7) (eq (send res1 :day) 26) (eq (send res1 :hour) 8) (eq (send res1 :minute) 48) (eq (send res1 :second) 33) (eq (send res1 :micro) 823)) [0m[0m
]2;[build] 1/4Trace:"?[0mmstart testing [test-json-decode-date]                               [0m[0m
]2;[build] 1/4]                                                                               [0m[0m
]2;[build] 1/4]                                                                               [0m[0m
]2;[build] 1/4decode.xml                                                                      [0m[0m
]2;[build] 1/4:16 UTC 2015  1.0.6))                                                           [0m[0m
]2;[build] 1/4).?[0m                                                                          [0m[0m
]2;[build] 1/4iled ... ( ?[0mmoutput to /home/travis/.r"                                      [0m[0m
]2;[build] 1/4Message:""                                                                      [0m[0m
]2;[build] 1/4-------------------------------------------------------------------------------- [0m[0m
]2;[build] 1/4                                                                                [0m[0m
]2;[build] 1/4                                                                                [0m[0m
]2;[build] 1/4SUMMARY                                                                         [0m[0m
]2;[build] 1/4[1;31m * RESULT: FAIL[0m                                                                 [0m[0m
]2;[build] 1/4 * TESTS: 8                                                                     [0m[0m
]2;[build] 1/4 * ERRORS: 0                                                                    [0m[0m
]2;[build] 1/4[1;31m * FAILURES: 1[0m                                                                  [0m[0m
```

**Comment by garaemon** [comment]
newer euslisp required?

**Comment by garaemon** [comment]
Hmmmm, it's difficult decision.

This test requires latest euslisp but one test includes test with release packages instead of shadow-fixed packages.

**Comment by garaemon** [comment]
Can you move the second test to allow_failures?

**Pull request merged**
