### PR TITLE
reset compile message flag

### PR DESCRIPTION
**Pull request by YoheiKakiuchi**

### CODE REVIEW

**Comment by k-okada** [comment]
let's add test program

**Comment by YoheiKakiuchi** [comment]
Added test program for compiling message
And related to https://github.com/jsk-ros-pkg/jsk_roseus/issues/333
add ros::load-message-with-compile macro for not using ```ros::*compile-message*``` flag explicitly

**Comment by k-okada** [comment]
```
(ros::load-ros-manifest "roseus_tutorials")
(ros::load-message-with-compile (ros::roseus-add-msgs "sensor_msgs"))
```
means if we wan to compile all messages, we have to add all of package using
`(ros::load-message-with-compile (ros::roseus-add-msgs "sensor_msgs"))`

or is there any problem if we compile all of messages?

--
◉ Kei Okada

**Comment by YoheiKakiuchi** [comment]
> is there any problem if we compile all of messages?

No, there is no problem.
I changed like that.
~~~
(ros::load-message-with-compile
 (ros::load-ros-manifest "roseus_tutorials")
 (ros::roseus-add-msgs "sensor_msgs"))
~~~

**Comment by k-okada** [comment]
what is the disadvantage of using `setq ros::*compile-message* t` ?

--
◉ Kei Okada

**Comment by YoheiKakiuchi** [comment]
when using "package://" for loading euslisp file, that file should be compiled.
https://github.com/jsk-ros-pkg/jsk_roseus/commit/7f93d700af380980f02098c7b9d6a8bb4a54a321
It's for files needed to compile, such as utility file for pointcloud.

**Comment by k-okada** [comment]
my question is:

what is the advantage of writing
```
(ros::load-message-with-compile
 (ros::load-ros-manifest "roseus_tutorials")
 (ros::roseus-add-msgs "sensor_msgs"))
```
than writing
```
(setq ros::*compile-files* t)
(ros::load-ros-manifest "roseus_tutorials")
(ros::roseus-add-msgs "sensor_msgs")
```



--
◉ Kei Okada

**Comment by YoheiKakiuchi** [comment]
using ros::load-message-with-compile prevent to forget unsetting compile-files flag.

**Comment by k-okada** [comment]
By the way, what is the expected behavior when we set `ros::*compile-message* t`, compile only message file?

**Comment by YoheiKakiuchi** [comment]
The expected behavior is not only compiling message, but also compiling ```package://somepackage/utilfile.l``` to ```somepackage_utilfile.so``` at ```~/.ros/roseus/<ros_distro>/```

**Comment by k-okada** [comment]
ok, as for message compile, i created another PR at #341 

as for compiling other files, do you want to compile only `(load "package://hogehoge/fugafuga.l")` or you wan to compile `(load "hogehoge.l")` too?

**Comment by YoheiKakiuchi** [comment]
I would like to compile only `(load "package://hogehoge/fugafuga.l")`

**Comment by k-okada** [comment]
ok, updated #341, but I think we'll want to compile whenever when we load source code... or is there any reason that you wan to compiling only package:// ?

**Comment by k-okada** [comment]
```
is there any reason that you wan to compiling only package:// ?
```
Ping @YoheiKakiuchi

**Comment by YoheiKakiuchi** [comment]
> is there any reason that you wan to compiling only package:// ?

No.
I had worry about where compiled code should be and naming problem (no minus character, different name with existing shared object).

**Comment by k-okada** [comment]
ok, please review #341

**Comment by k-okada** [comment]
since `(setq ros::*compile-message* t)` is defined under `ros` namespace, so it make sense to compile only files loaded via `package://`. If we introduce `(setq *compile-message* t)`, then we'll compile everything.

**Pull request closed without merging**
