### PR TITLE
[roseus_smach] check if top element is cons or not when dumping into dictionary in pickle::dump

### PR DESCRIPTION
**Pull request by knorth55**
```python
dict[key] = value
```
`key` must not be `list` in python.

this PR fixes bug in `pickle::dump`
when userdata with list something like this `'((:hoge ((1 2 3) (4 5 6)))))`,
`(1 2 3)` is used as a dict `key` as follows:

```python
dict["HOGE"] = {[1, 2, 3]: [4, 5, 6]}
```

I add check if dict key is `cons` or not.
When key is `cons`, use list as follows:

```python
dict["HOGE"] = [[1, 2, 3], [4, 5, 6]]
```

### CODE REVIEW

**Comment by Kanazawanaoaki** [comment]
I'm sorry. I don't really understand how this `pickle::dump` use. Is there a program that will generate a Python list or dict from the data converted by this?
I understand that if we publish `(pickle::dump '((:hoge ((1 2 3) (4 5 6)))))` data with a program like [this gist codes](https://gist.github.com/Kanazawanaoaki/a4db07e5762ae597714e71799d03d363 ), the output result will change and it will be treated as a list. However, I haven't been able to confirm whether or not an error occurs in python.  

before
```
$ rostopic echo /smach/container_status
header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
path: ''
initial_states: []
active_states: []
local_data: "(dS'HOGE'\n(d(lI1\naI2\naI3\na(dI4\n(lI5\naI6\nasss."
info: ''
---
```
after
```
$ rostopic echo /smach/container_status
header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
path: ''
initial_states: []
active_states: []
local_data: "(dS'HOGE'\n(l(dI1\n(lI2\naI3\nasI4\n(lI5\naI6\nasas."
info: ''
---
```

**Comment by knorth55** [comment]
Before
```python
In [6]: a = "(dS'HOGE'\n(d(lI1\naI2\naI3\na(dI4\n(lI5\naI6\nasss."

In [7]: a
Out[7]: "(dS'HOGE'\n(d(lI1\naI2\naI3\na(dI4\n(lI5\naI6\nasss."

In [8]: pickle.loads(a)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-7038544c8e94> in <module>()
----> 1 pickle.loads(a)

/usr/lib/python2.7/pickle.pyc in loads(str)
   1386 def loads(str):
   1387     file = StringIO(str)
-> 1388     return Unpickler(file).load()
   1389
   1390 # Doctest

/usr/lib/python2.7/pickle.pyc in load(self)
    862             while 1:
    863                 key = read(1)
--> 864                 dispatch[key](self)
    865         except _Stop, stopinst:
    866             return stopinst.value

/usr/lib/python2.7/pickle.pyc in load_setitem(self)
   1202         key = stack.pop()
   1203         dict = stack[-1]
-> 1204         dict[key] = value
   1205     dispatch[SETITEM] = load_setitem
   1206

TypeError: unhashable type: 'list'
```

after

```
In [9]: a = "(dS'HOGE'\n(l(dI1\n(lI2\naI3\nasI4\n(lI5\naI6\nasas."

In [11]: pickle.loads(a)
Out[11]: {'HOGE': [{1: [2, 3], 4: [5, 6]}]}

```

`pickle.loads` error occurs in `smach_viewer`.
https://github.com/ros-visualization/executive_smach_visualization/blob/melodic-devel/smach_viewer/scripts/smach_viewer.py#L185

**Comment by Kanazawanaoaki** [comment]
Thank you very much.
It was used for smach_viewer, I understand.
If it's okay to convert `'((:hoge ((1 2 3) (4 5 6))))` to `{'HOGE': [{1: [2, 3], 4: [5, 6]}]}`, then I think it's working!

By the way, when I wrote a [listener](https://gist.github.com/Kanazawanaoaki/a4db07e5762ae597714e71799d03d363#file-dump_listener_test-py ), the same result was obtained.

before
```
$ python dump_listener_test.py 
[ERROR] [1640755590.284514]: bad callback: <function callback at 0x7f9e729c1dd0>
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "dump_listener_test.py", line 8, in callback
    print (pickle.loads(msg.local_data))
  File "/usr/lib/python2.7/pickle.py", line 1388, in loads
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1204, in load_setitem
    dict[key] = value
TypeError: unhashable type: 'list'
```
after
```
$ python dump_listener_test.py 
{'HOGE': [{1: [2, 3], 4: [5, 6]}]}
```

**Comment by knorth55** [comment]
>If it's okay to convert '((:hoge ((1 2 3) (4 5 6)))) to {'HOGE': [{1: [2, 3], 4: [5, 6]}]}, then I think it's working!

Sorry, this is not a good example.
If you want to use A-list for userdata, you may use like below:
```
'((:hoge ((:fuga 2 3) (:foo 5 6))))
```

**Comment by Kanazawanaoaki** [comment]
I think I understand a little.  
In this example, it's easy to see that this PR has made it possible to handle it well.  
LGTM!  

before
```
$ python dump_listener_test.py 
[ERROR] [1641277970.781706]: bad callback: <function callback at 0x7f87fdde5dd0>
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "dump_listener_test.py", line 8, in callback
    print (pickle.loads(msg.local_data))
  File "/usr/lib/python2.7/pickle.py", line 1388, in loads
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1204, in load_setitem
    dict[key] = value
TypeError: unhashable type: 'list'
```
after
```
$ python dump_listener_test.py 
{'HOGE': [{'FUGA': [2, 3], 'FOO': [5, 6]}]}
```

**Review by Kanazawanaoaki — APPROVED** [review]

**Pull request merged**
