### PR TITLE
roseus_mongo: support non blocking insertion & update docstring

### PR DESCRIPTION
**Pull request by furushchev**
- Added non blocking insertion
- Added test code
- Added docstrings
- Fixed deprecated codes

### CODE REVIEW

**Comment by furushchev** [comment]
PLEASE DO NOT MERGE YET!

**Comment by furushchev** [comment]
Test failed on env:

    - ROS_DISTRO=hydro  USE_DEB=true
    - ROS_DISTRO=hydro  USE_DEB=true  NOT_TEST_INSTALL=true BEFORE_SCRIPT="git clone -b hydro-devel http://github.com/ros/geometry; git clone -b hydro-devel http://github.com/ros/geometry-experimental; touch jsk_roseus/roseus_tutorials/CATKIN_IGNORE; touch geometry-experimental/test_tf2/CATKIN_IGNORE" # need to ignore roseus_tutorials which depends on image_view2 and that install deb version of tf/tf2
    - ROS_DISTRO=hydro  USE_DEB=source

@k-okada Is it ok to move them to `allow_failures`? Since `hydro` is EOL and the last user is old PR2 who uses hydro but even the users have own `jsk_pr2.rosinstall` and does not use deb.

**Comment by furushchev** [comment]
```bash
Full test results for 'roseus_mongo/rosunit-test_mongo_client.xml'
-------------------------------------------------
<testsuite tests="3" failures="1" disabled="0" errors="0" time="0" name="AllTests">
  <testcase name="all-test" status="run" time="0" classname="all-test">
   <failure message="unbound variable" type="AssertionError">
Test:(ros::advertise mongo::*mongo-service-insert* mongodb_store_msgs::insert 10)
Trace:12
Message:"unbound variable"
   </failure>
  </testcase>
  <testcase name="mongo-client-param" status="run" time="0" classname="mongo-client-param">
  </testcase>
  <testcase name="mongo-client" status="run" time="0" classname="mongo-client">
  </testcase>
</testsuite>
```

`rosues_mongo` on hydro is old and does not support non wait insertion to db.
Disabled test it on hydro.

**Comment by furushchev** [comment]
On hydro installing `pip` fails maybe because `easy_install` is too old?

```bash
++ sudo easy_install pip==6.0.7
Searching for pip==6.0.7
Reading http://pypi.python.org/simple/pip/
Couldn't retrieve index page for 'pip'
Scanning index of all packages (this may take a while)
Reading http://pypi.python.org/simple/
No local packages or download links found for pip==6.0.7
error: Could not find suitable distribution for Requirement.parse('pip==6.0.7')
+++ error
+++ travis_time_end 31

**Comment by furushchev** [comment]
```

**Comment by snozawa** [comment]
I found the similar error on euslib's hydro travis test.

**Comment by furushchev** [comment]
Now tests are passed.
@k-okada  Please review / merge.

**Comment by k-okada** [comment]
done, please check @furushchev

**Comment by furushchev** [comment]
@k-okada Works well! Thank you very much!

**Pull request merged**
