### PR TITLE
[roseus_smach] Paralell executive state machine

### PR DESCRIPTION
**Pull request by furushchev**
- add feature to execute actions parallel
- add utility for creating new state machine (like DSL)
- add sample to use state machine with parallel action execution
- create readme of sample codes

### CODE REVIEW

**Comment by furushchev** [comment]
please do not merge this pullreq before merging https://github.com/jsk-ros-pkg/jsk_demos/pull/418
or it may occurs some unexpected errors.

**Comment by furushchev** [comment]
travis failed because of `euslisp`/`geneus` related error:

```
--------------------------------------------------------------------------------

testtest_genmsg ... FAILURE!

FAILURE: test [test_genmsg] did not generate test results

  File "/usr/lib/python2.7/unittest/case.py", line 327, in run

    testMethod()

  File "/opt/ros/hydro/lib/python2.7/dist-packages/rostest/runner.py", line 162, in fn

    self.assert_(os.path.isfile(test_file), "test [%s] did not generate test results"%test_name)

  File "/usr/lib/python2.7/unittest/case.py", line 420, in assertTrue

    raise self.failureException(msg)

--------------------------------------------------------------------------------



[ROSTEST]-----------------------------------------------------------------------



[testtest_geneus_dep1][failed]

[testtest_genmsg][failed]



SUMMARY

[1;31m * RESULT: FAIL[0m

 * TESTS: 0

 * ERRORS: 0

[1;31m * FAILURES: 2[0m



ERROR: The following tests failed to run:

 * testtest_geneus_dep1

 * testtest_genmsg
```

**Comment by furushchev** [comment]
what should I do?

**Comment by k-okada** [comment]
that's strange, I'll restart travis, including master branch to see what
going on.
https://travis-ci.org/jsk-ros-pkg/jsk_roseus/branches

--
◉ Kei Okada

**Comment by k-okada** [comment]
please merge origin/master, due to https://github.com/catkin/catkin_tools/pull/85, runing catkin within catkin run_test fails (test-genmsg.sh)

**Comment by h-kamada** [comment]
I want to use this commit. Please merge.

**Comment by k-okada** [comment]
still fails, pleas try if 
```
catkin build --verbose --catkin-make-args run_tests -- --limit-status-rate 0.001 jsk_roseus roseus roseus_smach roseus_tutorials -p4 --make-args -j8 --
```
works

**Comment by h-kamada** [comment]
There seems 2 errrors.

/home/h-kamada/ros/hydro_parent/devel/share/euslisp/jskeus/eus/Linux64/bin/irteusgl unittest-error: no such package ROSEUS_DEP2 in (read-from-string "(instance roseus_dep2::String :init)"), exitting...
[ERROR] test (read-from-string (instance roseus_dep2::String :init)) failed ... (no such package 45).


[ERROR] test (equal (send o method) data) failed ... ( std_msgs::byte :data -1 255

msgs]
ydro/build/roseus/test_results/roseus/rosunit-test_geneus.xml
 2015 0f0f62e 1.0.2))
).
std_msgs::bytemultiarray :data #i(1 2 3) /home/h-kamada/ros/hydro_parent/devel/share/euslisp/jskeus/eus/Linux64/bin/irteusgl unittest-error: symbol expected in (setq (elt ros::_data ros::i) (system:peek ros::buf ros::ptr- :char)), exitting...
[ERROR] test (setq (elt ros::_data ros::i) (system:peek ros::buf ros::ptr- :char)) failed ... (symbol expected 20).

**Pull request merged**
