### PR TITLE
[roseus_smach/CMakeLists.txt] dont include test dir for install directory

### PR DESCRIPTION
**Pull request by furushchev**

### CODE REVIEW

**Comment by k-okada** [comment]
why you remove test directory?

**Comment by furushchev** [comment]
I think test directory is not needed in install space.
Users using install space of packages installs apt version on which there are only test-passed version

**Comment by k-okada** [comment]
the reason why we added test directory into the install setting is to check
where if we forget to include another directory in to the deb package, for
example, when we forget to add launch, euslisp directory in the
instlal(DIRECTORY) macro, then the test aginst install directory fails.

--
◉ Kei Okada

**Comment by furushchev** [comment]
I understood. Thank you for explanation.

**Pull request closed without merging**
