### PR TITLE
Add test for bool array

### PR DESCRIPTION
**Pull request by snozawa**
Add test for bool array
https://github.com/jsk-ros-pkg/geneus/issues/38

Currently this test does not pass.

### CODE REVIEW

**Comment by k-okada** [comment]
I think adding Bool to
https://github.com/jsk-ros-pkg/jsk_roseus/blob/master/roseus/msg/FixedArray.msg
seems better,
if you added VariableArray.msg that contans same message FixedArray, that
would be very helpful

--
◉ Kei Okada

**Comment by snozawa** [comment]
Thankyou for your comment.
I could not found the message in FixedArray.msg:
```# This message is only for geneus```

So, I thought FixedArray.msg is used for user codes and it is difficult to change it.

I updated PR according to your comment.
I used FixedArray.msg by adding `bool_data` field and added VariableArray.msg similar to FixedArray.msg.

Currently, only `bool_data` in VariableArray.msg fails.

**Comment by k-okada** [comment]
FixedArray is only used for this test code, maybe we can change the name to
TestFixedArray of something.

--
◉ Kei Okada

**Comment by snozawa** [comment]
That's good idea. 
I updated PR by renaming FixedArray and VariableArray => FixedArrayForTest and VariableArrayFortest.

**Comment by k-okada** [comment]
moved to #336

**Pull request closed without merging**
