### PR TITLE
refactor roseus_tutorials

### PR DESCRIPTION
**Pull request by furushchev**
ref:
https://github.com/ros-interactive-manipulation/tabletop_object_perception/issues/1
https://github.com/ros-interactive-manipulation/tabletop_object_perception/pull/2

### CODE REVIEW

**Comment by furushchev** [comment]
wait for https://github.com/jsk-ros-pkg/jsk_travis/pull/235

**Comment by furushchev** [comment]
I rewrote tabletop object detection with jsk_pcl.
Now roseus_tutorials don't have to depend on ros-interactive-manipulation/tabletop_object_perception repository.

**Comment by furushchev** [comment]
Anyway current codes do not work. And this PR also includes refactoring codes.
Is it possible to merge after only removing dependency to tabletop_object_perception and disable test?

**Comment by furushchev** [comment]
Removed dependency to tabletop_object_perception
@k-okada How do you think about my previous comment?

**Comment by k-okada** [comment]
so you mean 
- use  tabletop_object_perception for demo ( or jsk_pcl_ros version )???
- add code using  tabletop_object_perception  into the roseus_tutorials, but do not add them to the test.

**Comment by furushchev** [comment]
@k-okada 
- there are already codes with `tabletop_object_perception` in `roseus_tutorials`
- I updated codes and now it supports if you download and compile the latest `tabletop_object_perception`
- New version of `tabletop` demo is in `jsk_pcl_ros` and it does no more depend on `roseus`.

**Comment by furushchev** [comment]
@k-okada How do you think of this?

**Comment by furushchev** [comment]
failed on some env. restarting

```
[roseus:make]   /opt/ros/jade/share/rostest/cmake/../../../bin/rostest --pkgdir=/workspace/ros/ws_jsk_roseus/src/jsk_roseus/roseus --package=roseus --results-filename test_test-multi-queue.xml --results-base-dir /workspace/ros/ws_jsk_roseus/build/roseus/test_results /workspace/ros/ws_jsk_roseus/src/jsk_roseus/roseus/test/test-multi-queue.test                                            
[roseus:make] INFO: cannot create a symlink to latest log directory: [Errno 17] File exists
[roseus:make] ... logging to /workspace/jsk-ros-pkg/jsk_roseus/log/rostest-93e6427f9ba0-12150.log
[roseus:make] ... logging to /workspace/jsk-ros-pkg/jsk_roseus/log/rostest-93e6427f9ba0-12151.log
[roseus:make] [ROSUNIT] Outputting test results to /workspace/ros/ws_jsk_roseus/build/roseus/test_results/roseus/rostest-test_test-compile-message.xml
[roseus:make] Traceback (most recent call last):
[roseus:make]   File "/opt/ros/jade/share/rostest/cmake/../../../bin/rostest", line 36, in     
[roseus:make]     rostestmain()
[roseus:make]   File "/opt/ros/jade/lib/python2.7/dist-packages/rostest/__init__.py", line 273, in rostestmain                               
[roseus:make]     _main()                                                             
[roseus:make]   File "/opt/ros/jade/lib/python2.7/dist-packages/rostest/rostest_main.py", line 167, in rostestmain                                        
[roseus:make]     results_file = xmlResultsFile(pkg, outname, is_rostest, env=env)                                                             
[roseus:make]   File "/opt/ros/jade/lib/python2.7/dist-packages/rosunit/core.py", line 102, in xml_results_file
[roseus:make]     raise IOError("cannot create test results directory [%s]. Please check permissions."%(test_dir))                                                       
[roseus:make] IOError: cannot create test results directory [/workspace/ros/ws_jsk_roseus/build/roseus/test_results/roseus]. Please check permissions.
```

**Comment by furushchev** [comment]
travis passed.
@k-okada How do you think of merging this PR? (refer: https://github.com/jsk-ros-pkg/jsk_roseus/pull/436#issuecomment-209867814 )

**Pull request merged**
