### PR TITLE
use new genmsg

### PR DESCRIPTION
**Pull request by k-okada**
@garaemon, this is workaround for using new geneus messages generator, which packae should I test, jsk_control? jsk_pcl_ros?
I also afraid that we should not run this script on ros buildfirm once new geneus is accepted.

- add example to use new generate_all_roseus_messages()
- add new macro, generate_all_roseus_message() to generate all dependency  msgs using new geneus written by python

### CODE REVIEW

**Comment by garaemon** [comment]
I think these macros shoud be tested on 'demo' packages.For example, detect_cans blah blah blah and drc blah blah. And jsk_perception.







I'm afraid that it can work if two packages use this macros.




For example, jsk_perception depends on jsk_pcl_ros and if jsk_pcl_ros and jsk_perception uses this macro, what will happen?


✉︎ Ryohei

**Comment by k-okada** [comment]
ok, I have checked with jsk_demo package and confirmed it works, One improvement is that we removed `generate_all_roseus_messages()` so everything works fine without any modification.

1) release new geneus(jsk-ros-pkg/geneus) on hydro
2) remove geneus from jsk_roseus

**Comment by garaemon** [comment]
great!

**Comment by k-okada** [comment]
we have to switch to new geneus, see https://github.com/jsk-ros-pkg/jsk_roseus/pull/205

**Pull request merged**
