### PR TITLE
test/unittest.l: check results numbers

### PR DESCRIPTION
**Pull request by k-okada**
this should fail until https://github.com/euslisp/EusLisp/pull/6 is merged

### CODE REVIEW

**Comment by k-okada** [comment]
@snozawa , could double check test/unitest.l ? it is failing on my machine and https://travis-ci.org/euslisp/EusLisp/builds/120032277

```
+ irteusgl irteus/test/unittest.l
configuring by "/home/k-okada/jskeus/eus/lib/eusrt.l"
;; readmacro ;; object ;; packsym ;; common ;; constants ;; stream ;; string ;; loader ;; pprint ;; process ;; hashtab ;; array ;; mathtran ;; eusdebug ;; eusforeign ;; coordinates ;; tty ;; history ;; toplevel ;; trans ;; comp ;; builtins ;; par ;; intersection ;; geoclasses ;; geopack ;; geobody ;; primt ;; compose ;; polygon ;; viewing ;; viewport ;; viewsurface ;; hid ;; shadow ;; bodyrel ;; dda ;; helpsub ;; eushelp ;; xforeign ;; Xdecl ;; Xgraphics ;; Xcolor ;; Xeus ;; Xevent ;; Xpanel ;; Xitem ;; Xtext ;; Xmenu ;; Xscroll ;; Xcanvas ;; Xtop ;; Xapplwin 
Xserver connection failed;; pixword ;; RGBHLS ;; convolve ;; piximage ;; pbmfile ;; image_correlation ;; oglforeign ;; gldecl ;; glconst ;; glforeign ;; gluconst ;; gluforeign ;; glxconst ;; glxforeign ;; eglforeign ;; eglfunc ;; glutil ;; gltexture ;; glprim ;; gleus ;; glview ;; toiv-undefined ;; fstringdouble irtmath irtutil irtc irtgeoc irtgraph pgsql irtgeo euspqp pqp irtscene irtmodel irtdyna irtrobot irtsensor irtbvh irtcollada irtpointcloud irtx eusjpeg euspng png irtimage irtglrgb 
;; extending gcstack 0x4bee560[16374] --> 0x5024d00[32748] top=3c7c
irtgl irtviewer 
EusLisp 9.17(29f108a 11731a8) for Linux64 created on kokada-t440s(Fri Apr 1 19:44:33 JST 2016)
TEST-NAME: test1
  now testing...
start testing [test1]
TEST-NAME: test2
  now testing...
start testing [test2]
TEST-NAME: test3
  now testing...
start testing [test3]
TEST-NAME: test4
  now testing...
start testing [test4]
*** This test  fails intentinally ****
[ERROR] test nil failed ... (false ^[0mm*** This test  fails intentinally ****
eated on kokada-t440s(Fri Apr 1 19:44:33 JST 2016)^[0m�).
[ERROR] test nil failed ... (false  2016)^[0m�).^[0m
il failed ... (false ^[0mm*** This test  fails intentinally ****
eated on kokada-t440s(Fri Apr 1 19:44:33 JST).
[ERROR] test nil failed ... (false d on kokada-t440s(Fri Apr 1 19:44:33 JST).^[0m
[0m�).^[0m
il failed ... (false ^[0mm*** This test  fails intentinally ****
eate).
[ERROR] test nil failed ... (false  This test  fails intentinally ****
eate).^[0m
kada-t440s(Fri Apr 1 19:44:33 JST).^[0m
[0m�).^[0m
il failed ... (false ^[0mm***).
[ERROR] test nil failed ... (false 0m�).^[0m
il failed ... (false ^[0mm***).^[0m
est  fails intentinally ****
eate).^[0m
kada-t440s(Fri Apr 1 19:44:33 JST).^[0m
[).
[ERROR] test nil failed ... (false ada-t440s(Fri Apr 1 19:44:33 JST).^[0m
[).^[0m
[0m
il failed ... (false ^[0mm***).^[0m
est  fails intentinally ****
eate).^[0m
k).
[ERROR] test nil failed ... (false st  fails intentinally ****
eate).^[0m
k).^[0m
0s(Fri Apr 1 19:44:33 JST).^[0m
[).^[0m
[0m
il failed ... (false ^[0mm***).^[0m
e).
[ERROR] test nil failed ... (false 0m
il failed ... (false ^[0mm***).^[0m
e).^[0m
ls intentinally ****
eate).^[0m
k).^[0m
0s(Fri Apr 1 19:44:33 JST).^[0m
[).^[0m
[).
[ERROR] test nil failed ... (false s(Fri Apr 1 19:44:33 JST).^[0m
[).^[0m
[).^[0m
ailed ... (false ^[0mm***).^[0m
e).^[0m
ls intentinally ****
eate).^[0m
k).^[0m
0).
[ERROR] test nil failed ... (false s intentinally ****
eate).^[0m
k).^[0m
0).^[0m
pr 1 19:44:33 JST).^[0m
[).^[0m
[).^[0m
ailed ... (false ^[0mm***).^[0m
e).^[0m
l).
ALL RESULTS:
  TEST-NUM: 4
    PASSED:   4
    FAILURE:  0
RESULT: all-test
  TEST-NUM: 0
    PASSED:   0
    FAILURE:  0
RESULT: test1
  TEST-NUM: 1
    PASSED:   1
    FAILURE:  0
RESULT: test2
  TEST-NUM: 1
    PASSED:   1
    FAILURE:  0
RESULT: test3
  TEST-NUM: 1
    PASSED:   1
    FAILURE:  0
RESULT: test4
  TEST-NUM: 1
    PASSED:   1
    FAILURE:  0
functions = 4
```

**Comment by k-okada** [comment]
on jskeus, unitest.l is ignored... -> https://github.com/euslisp/jskeus/commit/9a8e2fd71a7caa7f2914bbe900b7bad65cf8e2c4

**Comment by k-okada** [comment]
on euslisp, nittest is runing, but not working as we expected (we assume one test is failing, but all test passed in log file)
https://s3.amazonaws.com/archive.travis-ci.org/jobs/117872981/log.txt

**Comment by snozawa** [comment]
https://github.com/jsk-ros-pkg/jsk_roseus/pull/21#issuecomment-204349389

In this case, what do you mean "failing"?
Is "failing" like the following?:
- the number of `FAILURE:` of `ALL RESULTS:` from unittest.l print message is `0`
- return code from irteusgl are not 0

(e.g., unittest.l printing says success, but return code says failure).

If so, `irteus/test/unittest.l` fails on my PC as your PC and travis.
(My PC is ubuntu 12.04 and euslisp version is `EusLisp 9.12(9e84bdb 1.0.3)`).

```
nozawa@W540-nozawa:~/ros/hydro_parent/src/jskeus$ irteusgl irteus/test/unittest.l || echo "Failed"
configuring by "/home/nozawa/ros/hydro_parent/devel/share/euslisp/jskeus/eus//lib/eusrt.l"
;; readmacro ;; object ;; packsym ;; common ;; constants ;; stream ;; string ;; loader ;; pprint ;; process ;; hashtab ;; array ;; mathtran ;; eusdebug ;; eusforeign ;; coordinates ;; tty ;; history ;; toplevel ;; trans ;; comp ;; builtins ;; par ;; intersection ;; geoclasses ;; geopack ;; geobody ;; primt ;; compose ;; polygon ;; viewing ;; viewport ;; viewsurface ;; hid ;; shadow ;; bodyrel ;; dda ;; helpsub ;; eushelp ;; xforeign ;; Xdecl ;; Xgraphics ;; Xcolor ;; Xeus ;; Xevent ;; Xpanel ;; Xitem ;; Xtext ;; Xmenu ;; Xscroll ;; Xcanvas ;; Xtop ;; Xapplwin 
connected to Xserver DISPLAY=:0.0
X events are being asynchronously monitored.
;; pixword ;; RGBHLS ;; convolve ;; piximage ;; pbmfile ;; image_correlation ;; oglforeign ;; gldecl ;; glconst ;; glforeign ;; gluconst ;; gluforeign ;; glxconst ;; glxforeign ;; eglforeign ;; eglfunc ;; glutil ;; gltexture ;; glprim ;; gleus ;; glview ;; toiv-undefined ;; fstringdouble irtmath irtutil irtc irtgeoc irtgraph pgsql irtgeo euspqp pqp irtscene irtmodel irtdyna irtrobot irtsensor irtbvh irtcollada irtpointcloud irtx eusjpeg euspng png irtimage irtglrgb 
;; extending gcstack 0x5ae6de0[16374] --> 0x5f43390[32748] top=3c7a
irtgl irtviewer                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
EusLisp 9.12(9e84bdb 1.0.3) for Linux64 created on W540-nozawa(Sun Mar 20 22:37:45 JST 2016)
TEST-NAME: test1
  now testing...
start testing [test1]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
TEST-NAME: test2
  now testing...
start testing [test2]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
TEST-NAME: test3
  now testing...
start testing [test3]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
TEST-NAME: test4
  now testing...
start testing [test4]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
*** This test  fails intentinally ****                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
[ERROR] test nil failed ... (false ^[0mm*** This test  fails intentinally ****                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
ted on W540-nozawa(Sun Mar 20 22:37:45 JST 2016)^[0m\310׭^E).
[ERROR] test nil failed ... (false 016)^[0m\310׭^E).^[0m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
il failed ... (false ^[0mm*** This test  fails intentinally ****                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
ted on W540-nozawa(Sun Mar 20 22:37:45 JST 2).
[ERROR] test nil failed ... (false on W540-nozawa(Sun Mar 20 22:37:45 JST 2).^[0m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
m\310׭^E).^[0m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
il failed ... (false ^[0mm*** This test  fails intentinally ****                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
ted ).
[ERROR] test nil failed ... (false  This test  fails intentinally ****                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
ted ).^[0m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
-nozawa(Sun Mar 20 22:37:45 JST 2).^[0m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
m\310׭^E).^[0m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
il failed ... (false ^[0mm***).
[ERROR] test nil failed ... (false \310׭^E).^[0m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
il failed ... (false ^[0mm***).^[0m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
est  fails intentinally ****                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
ted ).^[0m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
-nozawa(Sun Mar 20 22:37:45 JST 2).^[0m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
m).
[ERROR] test nil failed ... (false nozawa(Sun Mar 20 22:37:45 JST 2).^[0m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
m).^[0m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
[0m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
il failed ... (false ^[0mm***).^[0m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
est  fails intentinally ****                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
ted ).^[0m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
-).
[ERROR] test nil failed ... (false st  fails intentinally ****                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
ted ).^[0m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
-).^[0m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
Sun Mar 20 22:37:45 JST 2).^[0m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
m).^[0m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
[0m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
il failed ... (false ^[0mm***).^[0m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
e).
[ERROR] test nil failed ... (false 0m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
il failed ... (false ^[0mm***).^[0m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
e).^[0m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
ls intentinally ****                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
ted ).^[0m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
-).^[0m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
Sun Mar 20 22:37:45 JST 2).^[0m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
m).^[0m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
[).
[ERROR] test nil failed ... (false un Mar 20 22:37:45 JST 2).^[0m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
m).^[0m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
[).^[0m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
ailed ... (false ^[0mm***).^[0m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
e).^[0m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
ls intentinally ****                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
ted ).^[0m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
-).^[0m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
S).
[ERROR] test nil failed ... (false s intentinally ****                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
ted ).^[0m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
-).^[0m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
S).^[0m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
20 22:37:45 JST 2).^[0m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
m).^[0m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
[).^[0m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
ailed ... (false ^[0mm***).^[0m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
e).^[0m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
l).
ALL RESULTS:
  TEST-NUM: 4
    PASSED:   4
    FAILURE:  0
RESULT: all-test
  TEST-NUM: 0
    PASSED:   0
    FAILURE:  0
RESULT: test1
  TEST-NUM: 1
    PASSED:   1
    FAILURE:  0
RESULT: test2
  TEST-NUM: 1
    PASSED:   1
    FAILURE:  0
RESULT: test3
  TEST-NUM: 1
    PASSED:   1
    FAILURE:  0
RESULT: test4
  TEST-NUM: 1
    PASSED:   1
    FAILURE:  0
functions = 4
Failed
```

**Comment by snozawa** [comment]
https://github.com/jsk-ros-pkg/jsk_roseus/pull/21#issuecomment-204355655
> on euslisp, nittest is runing, but not working as we expected (we assume one test is failing, but all test passed in log file)
> https://s3.amazonaws.com/archive.travis-ci.org/jobs/117872981/log.txt

Hmmm, as you said, 
in euslisp/euslisp travis test, `irteus/test/unittest.l` is running differently from euslisp/jskeus travis test.
However, the euslisp/euslisp travis test does not fail.

**Comment by k-okada** [comment]
this code assuming, 3 tests succeeded and 1 test failing. but it seems all test passed.
```
+(send *unit-test* :result)
 +(if (and (= (length (send *unit-test* :functions)) 4)
 +         (= (apply #'+ (send-all (send *unit-test* :result) :num-tests)) 4)
 +         (= (apply #'+ (send-all (send *unit-test* :result) :num-failures)) 1)
 +         (= (apply #'+ (send-all (send *unit-test* :result) :num-successes)) 3))
 +    (setq ret 0))
```
```
ALL RESULTS:
  TEST-NUM: 4
    PASSED:   4
    FAILURE:  0
```

**Comment by k-okada** [comment]
The reason euslisp/euslisp did not fail is 
```
  - export EXIT_STATUS=0; for test_l in irteus/test/*.l; do irteusgl $test_l; export EXIT_STATUS=$?; done; [ $EXIT_STATUS == 0 ]
```
only tests (` [ $EXIT_STATUS == 0 ]`) on last result, it is  just check the last file in `test/*.l`

**Comment by snozawa** [comment]
Create PR to add more print mesage from unittest.l:
https://github.com/euslisp/jskeus/pull/358

On my PC, the results are:
```
functions = 4, num-tests =4, num-failures = 0, num-successes = 4
return code = -1
```

**Comment by snozawa** [comment]
> only tests ([ $EXIT_STATUS == 0 ]) on last result, it is just check the last file in test/*.l

I see!!

**Comment by snozawa** [comment]
If i use the following `irteus/test/unittest.l`, the behaviour seem to be desired one:
```
;; test code for unittest                                                                                                                                                                                                                 

(require :unittest "lib/llib/unittest.l")
(init-unit-test)

(deftest test1
  )

(deftest test2
  (dotimes (i 10)
    (assert t "true"))
  )

(deftest test3
  (dotimes (i 10)
    (assert (null nil) "false"))
  )

(deftest test4
  (dotimes (i 10)
    (assert t "ok"))
  (warning-message 1 "*** This test  fails intentinally ****~%")
  (dotimes (i 10)
    (assert nil "false")
    ;; force remove trace from expected errored test                                                                                                                                                                                      
    ;;(setq ((car (*unit-test* . result)) . failures) nil) ;; COMMENT OUT HERE!!!!      
    )
  (dotimes (i 10)
    (assert t "ok"))
  )

;; Prevent from exitting from run-all-tests
(setf (symbol-function 'org-exit) (symbol-function 'exit))
(setf (symbol-function 'exit) #'(lambda (a) (print a)))
(run-all-tests)
(setf (symbol-function 'exit) (symbol-function 'org-exit))

(setq ret -1)
(format t "functions = ~A, num-tests =~A, num-failures = ~A, num-successes = ~A~%"
        (length (send *unit-test* :functions))
        (apply #'+ (send-all (send *unit-test* :result) :num-tests))
        (apply #'+ (send-all (send *unit-test* :result) :num-failures))
        (apply #'+ (send-all (send *unit-test* :result) :num-successes)))
(send *unit-test* :result)
(if (and (= (length (send *unit-test* :functions)) 4)
         (= (apply #'+ (send-all (send *unit-test* :result) :num-tests)) 4)
         (= (apply #'+ (send-all (send *unit-test* :result) :num-failures)) 1)
         (= (apply #'+ (send-all (send *unit-test* :result) :num-successes)) 3))
    (setq ret 0))
(format t "return code = ~A~%" ret)
(exit ret)
```
The results are:
```
functions = 4, num-tests =4, num-failures = 1, num-successes = 3
return code = 0
```

In `test4`, why are failures removed?
```
    ;; force remove trace from expected errored test                    
    (setq ((car (*unit-test* . result)) . failures) nil)          
```

**Comment by k-okada** [comment]
On Fri, Apr 1, 2016 at 11:27 PM, Shunichi Nozawa <notifications@github.com>
wrote:

> ;; force remove trace from expected errored test (setq ((car (*unit-test*
> . result)) . failures) nil)


I do not remember.... sorry. if we can get expected behavior without this,
we can remove this line

--
◉ Kei Okada

**Comment by snozawa** [comment]
I enabled unittest.l on jskeus travis test:
https://github.com/euslisp/jskeus/pull/359
I fixed checking of exit status in euslisp travis test:
https://github.com/euslisp/EusLisp/pull/170

`irteus/test/unittest.l` is enabled, but please not that some bug on `lib/llib/unittest.l` cannot be trapped:
https://github.com/jsk-ros-pkg/jsk_roseus/pull/21#issuecomment-42674219

**Pull request merged**
