### PR TITLE
use original source (do not use rosmake proxy package) for euslisp

### PR DESCRIPTION
**Pull request by k-okada**
let me explain what we do in this PR:
- jsk_roseus/euslisp no longer exists, we do not have euslisp/jskeus "ROS" package anymore
- instead of that, we create new euslisp-release jskeus-release package, see https://github.com/tork-a/euslisp-release/tree/master ( should we host this repository within jsk-ros-pkg?), this repo will used for releasing as deb file
- the release package will add patch files (https://github.com/tork-a/euslisp-release/tree/master/patches) to the original source (http://github.com/euslisp/EusLisp direcotry, they usually call upstream repository) and do release job
- you can see current "release" source from https://github.com/tork-a/euslisp-release, that will include original source + patches for ROS release, so if you download this repository, you can compile as ros package, so I include this to https://github.com/k-okada/jsk_roseus/blob/use_origin_code/.rosinstall
- you have to change original source to modify euslisp/jskeus, if you changed release source, it will overwritten in next release, to download original source code into your catkin workspace, please use https://github.com/k-okada/jsk_roseus/blob/use_origin_code/setup.sh
- you have to use catkin_make_isolated, or catkin tool instead of using catkin_make, I strongly recommend to use "catkin"

### CODE REVIEW

**Comment by garaemon** [comment]
> you have to use catkin_make_isolated, or catkin tool instead of using catkin_make, I strongly recommend to use "catkin"

catkin build? Is it always compile catkin packages isolated? How long does it take to compile?

**Comment by garaemon** [comment]
`catkin build` looks  better and faster than catkin_make.

However, I cannot compile jsk_pcl_ros with caktin build.
```
-- Found PCL: /usr/lib/libboost_system-mt.so;/usr/lib/libboost_filesystem-mt.so;/usr/lib/libboost_thread-mt.so;/usr/lib/libboost_date_time-mt.so;/usr/lib/libboost_iostreams-mt.so;/usr/lib/libboost_serialization-mt.so;optimized;/usr/lib/libpcl_common.so;debug;/usr/lib/libpcl_common.so;optimized;/usr/lib/libflann_cpp_s.a;debug;/usr/lib/libflann_cpp_s.a;optimized;/usr/lib/libpcl_kdtree.so;debug;/usr/lib/libpcl_kdtree.so;optimized;/usr/lib/libpcl_octree.so;debug;/usr/lib/libpcl_octree.so;optimized;/usr/lib/libpcl_search.so;debug;/usr/lib/libpcl_search.so;/usr/lib/libOpenNI.so;vtkCommon;vtkRendering;vtkHybrid;vtkCharts;optimized;/usr/lib/libpcl_io.so;debug;/usr/lib/libpcl_io.so;optimized;/usr/lib/libpcl_sample_consensus.so;debug;/usr/lib/libpcl_sample_consensus.so;optimized;/usr/lib/libpcl_filters.so;debug;/usr/lib/libpcl_filters.so;optimized;/usr/lib/libpcl_visualization.so;debug;/usr/lib/libpcl_visualization.so;optimized;/usr/lib/libpcl_outofcore.so;debug;/usr/lib/libpcl_outofcore.so;optimized;/usr/lib/libpcl_features.so;debug;/usr/lib/libpcl_features.so;optimized;/usr/lib/libpcl_segmentation.so;debug;/usr/lib/libpcl_segmentation.so;optimized;/usr/lib/libpcl_people.so;debug;/usr/lib/libpcl_people.so;optimized;/usr/lib/libpcl_registration.so;debug;/usr/lib/libpcl_registration.so;optimized;/usr/lib/libpcl_recognition.so;debug;/usr/lib/libpcl_recognition.so;optimized;/usr/lib/libpcl_keypoints.so;debug;/usr/lib/libpcl_keypoints.so;optimized;/usr/lib/libqhull.so;debug;/usr/lib/libqhull.so;optimized;/usr/lib/libpcl_surface.so;debug;/usr/lib/libpcl_surface.so;optimized;/usr/lib/libpcl_tracking.so;debug;/usr/lib/libpcl_tracking.so;optimized;/usr/lib/libpcl_apps.so;debug;/usr/lib/libpcl_apps.so;/usr/lib/libboost_system-mt.so;/usr/lib/libboost_filesystem-mt.so;/usr/lib/libboost_thread-mt.so;/usr/lib/libboost_date_time-mt.so;/usr/lib/libboost_iostreams-mt.so;/usr/lib/libboost_serialization-mt.so;optimized;/usr/lib/libqhull.so;debug;/usr/lib/libqhull.so;/usr/lib/libOpenNI.so;optimized;/usr/lib/libflann_cpp_s.a;debug;/usr/lib/libflann_cpp_s.a;vtkCommon;vtkRendering;vtkHybrid;vtkCharts 
CMake Error at catkin.cmake:123 (include):
  include could not find load file:

    /home/lueda/ros/hydro/devel/share/jsk_topic_tools/cmake/nodelet.cmake
Call Stack (most recent call first):
  CMakeLists.txt:12 (include)


-- jsk_pcl_ros: 25 messages, 15 services
-- Configuring incomplete, errors occurred!
[jsk_pcl_ros] <== '/home/lueda/ros/hydro/build/jsk_pcl_ros/build_env.sh /usr/bin/cmake /home/lueda/ros/hydro/src/jsk-ros-pkg/jsk_recognition/jsk_pcl_ros -DCATKIN_DEVEL_PREFIX=/home/lueda/ros/hydro/devel -DCMAKE_INSTALL_PREFIX=/home/lueda/ros/hydro/install' failed with return code '1'
                                                                                                                                               
[build] There were errors:                                                                                                                    

    Failed to build package 'jsk_pcl_ros' because the following command:

        # Command run in directory: /home/lueda/ros/hydro/build/jsk_pcl_ros
        /home/lueda/ros/hydro/build/jsk_pcl_ros/build_env.sh /usr/bin/cmake /home/lueda/ros/hydro/src/jsk-ros-pkg/jsk_recognition/jsk_pcl_ros -DCATKIN_DEVEL_PREFIX=/home/lueda/ros/hydro/devel -DCMAKE_INSTALL_PREFIX=/home/lueda/ros/hydro/install

    Exited with return code: 1 
[build] Runtime: 7.3 seconds 

```

**Comment by garaemon** [comment]
Have you checked all the cakin packages we have can be compiled with `catkin build`?

**Comment by garaemon** [comment]
If we use catkin tools, we need to run `catkin build` for all the packages where we want to `roscd`.

```
$ echo $ROS_PACKAGE_PATH 
/home/lueda/ros/hydro/src/laser_geometryr_msgs:/home/lueda/ros/hydro/src/jsk-ros-pkg/jsk_common/3rdparty/sklearn:/home/lueda/ros/hydro/src/jsk-ros-pkg/jsk_common/jsk_gui_msgs:/home/lueda/ros/hydro/src/jsk-ros-pkg/jsk_common/jsk_footstep_msgs:/home/lueda/ros/hydro/src/jsk-ros-pkg/jsk_common/jsk_coordination_system/dynamic_tf_publisher:/home/lueda/ros/hydro/src/jsk-ros-pkg/jsk_common/jsk_hark_msgs:/home/lueda/ros/hydro/src/jsk-ros-pkg/jsk_roseus/euslisp:/home/lueda/ros/hydro/src/jsk-ros-pkg/jsk_roseus/geneus:/home/lueda/ros/hydro/src/jsk-ros-pkg/jsk_common/jsk_topic_tools:/home/lueda/ros/hydro/src/perception_pcl/pcl_ros:/home/lueda/ros/hydro/src/jsk-ros-pkg/jsk_roseus/roseus:/home/lueda/ros/hydro/src/rviz:/home/lueda/ros/hydro/src/jsk-ros-pkg/jsk_common/jsk_ros_patch/image_view2:/home/lueda/ros/hydro/src/jsk-ros-pkg/jsk_recognition/jsk_pcl_ros:/home/lueda/ros/hydro/src/jsk-ros-pkg/jsk_visualization/jsk_rviz_plugins:/home/lueda/ros/hydro/src/jsk-ros-pkg/jsk_control/jsk_footstep_planner:/home/lueda/ros/hydro/src/jsk-ros-pkg/jsk_control/jsk_footstep_controller:/home/lueda/ros/hydro/src/jsk-ros-pkg/jsk_common/posedetection_msgs:/home/lueda/ros/hydro/src/jsk-ros-pkg/jsk_common/3rdparty/libsiftfast:/opt/ros/hydro/share:/opt/ros/hydro/stacks
```

**Comment by garaemon** [comment]
jsk_recognition should be compilable with `catkin build` now
https://github.com/jsk-ros-pkg/jsk_recognition/pull/635

**Comment by garaemon** [comment]
I think it's a little bit early to merge it...

Do we need to install all the files such as launch when we use catkin build?

**Comment by k-okada** [comment]
> Do we need to install all the files such as launch when we use catkin 
build?

it not for source compile, but for deb release

--
◉ Kei Okada

**Pull request merged**
