### PR TITLE
[roseus_smach] add return value option of action client state

### PR DESCRIPTION
**Pull request by furushchev**

### CODE REVIEW

**Comment by furushchev** [comment]
Travis passed. Please merge!

**Comment by garaemon** [comment]
merge origin/master

**Comment by furushchev** [comment]
@garaemon thanks for advice!
merge is done

**Comment by k-okada** [comment]
can we close this PR

**Comment by furushchev** [comment]
@k-okada before close, please merge.

**Comment by k-okada** [comment]
I think these are no diffs to merge, so I just close this

**Comment by furushchev** [comment]
@k-okada It's ok to close. Thanks!

**Pull request closed without merging**
