### PR TITLE
roseus.cpp: add ros::create-timer function

### PR DESCRIPTION
**Pull request by k-okada**
based on http://wiki.ros.org/roscpp/Overview/Timers, see #237

currently, proposed API is something like this.

```
(defun cb1 (event)
  (let (msg)
    (setq msg (instance std_msgs::string :init))
    (send msg :data (format nil "hello world ~a" (send (ros::time-now) :sec-nsec)))
    (ros::publish "chatter1" msg)
    ))
(ros::create-timer 0.1 #'cb1)
```

another possibility is
```
(ros::create-timer ros::Timer(0.1) #'cb1)
```

I also did not implement ros::TimerEvent class(http://wiki.ros.org/roscpp/Overview/Timers#Callback_Signature), does it should be class instance? or just to pass 
`(list last_expected last_real current_expected current_real profile.last_duration)` is ok for you?

### CODE REVIEW

**Comment by k-okada** [comment]
if you register a callback function twice as
```
(ros::create-timer 0.1 #'cb1)
(ros::create-timer 0.1 #'cb1)
```
then later one is enabled, previous callback function is removed

but when you call
```
(ros::create-timer 0.1 #'(lambda (msg) ))
(ros::create-timer 0.1 #'(lambda (msg) ))
```
Then two function is registered. Currently there are no mean to remove lambda function from callback queues.

**Comment by garaemon** [comment]
Is the callback run in single thread?

**Comment by k-okada** [comment]
It depends on roscpp implementation, and it seems they're using thread for each timer object -> https://github.com/ros/ros_comm/blob/4bbda4a0bfd1ed774fafab7920e4ce557f8c00b9/clients/roscpp/include/ros/timer_manager.h#L313

**Comment by k-okada** [comment]
added timer-event class and pass to callback function

**Comment by garaemon** [comment]
I will merge this and release new version.

**Comment by garaemon** [comment]
1.3.9 has been released

**Pull request merged**
