### PR TITLE
fix make-state-machine docstring

### PR DESCRIPTION
**Pull request by knorth55**
`'function` (not `#'function`) is correct way to set state function, otherwise it causes `segmentation fault`
cc. @Affonso-Gui

### CODE REVIEW

**Comment by knorth55** [comment]
what does ideally-should-be mean?

**Comment by furushchev** [comment]
In lisp, a function symbol should always be with `#'`.

**Comment by knorth55** [comment]
hmm, in that case, we need to change the function?

**Comment by furushchev** [comment]
No, I'm just proposing to add the docs about why we have to use `'` instead of `#'`.
Without mentioning it, it will be hard to assume, for instance, `action-a` is a function from the docstring.

**Comment by Affonso-Gui** [comment]
Using `#'` appears to cause some interference with eus closure system.

From `state-machine-sample` :
```
#!/usr/bin/env roseus

(load "package://roseus_smach/src/state-machine.l")
(load "package://roseus_smach/src/state-machine-ros.l")
(load "package://roseus_smach/src/state-machine-utils.l")

(ros::roseus "test")

(setq count 0)
(defun func-foo (&rest args)
  (format t "Execute state FOO~%")
  (cond ((< count 3) (incf count) :outcome1)
	(t :outcome2)))
(defun func-bar (&rest args)
  (format t "Execute state BAR~%")
  :outcome2)

(defun smach-simple ()
  (let ((sm (instance state-machine :init)))
    (send sm :add-node (instance state :init :FOO #'func-foo))
    (send sm :add-node (instance state :init :BAR #'func-bar))
    ;; goal-states are generated in this method
    (send sm :goal-state (list :outcome4 :outcome5))

    ;; select a node as start-node
    (send sm :start-state :FOO)
    ;; from and to nodes are selected by name or symbol
    (send sm :add-transition :FOO :BAR :outcome1)
    (send sm :add-transition :FOO :outcome4 :outcome2)
    (send sm :add-transition :BAR :FOO :outcome2)
    sm ))

(exec-state-machine (smach-simple))

;; eustf roseus_c_util Execute state FOO
;; Segmentation Fault.
;; in (< count 3)
;; You are still in a signal handler.
;;Try reset or throw to upper level as soon as possible.
;; code=728068912 x=2b657200 addr=dc8893b372845b40
;; Fatal: 
```

Also,  [test code](https://github.com/jsk-ros-pkg/jsk_roseus/blob/cbb4f1ac657ba29d751e1ad3e416143732bf99a7/roseus_smach/test/test-roseus-smach-utils.l) also seems to avoid the `#'` notation.

PS.: In a different note, am I the only one that would be glad to have an expandable `make-state-machine` macro (instead of a function) ?

**Comment by knorth55** [comment]
it seems that global variable is in `func-foo`.

**Comment by Affonso-Gui** [comment]
@furushchev ping

**Comment by furushchev** [comment]
@knorth55 @Affonso-Gui pong. I still don't see any update on the PR.

**Comment by Affonso-Gui** [comment]
@furushchev Sorry for the delay. Just updated the documentation in https://github.com/jsk-ros-pkg/jsk_roseus/pull/595

**Pull request merged**
