### PR TITLE
[roseus][roseus.cpp] check ros::ok() in ros::spin

### LINKED ISSUE #529: roseus is left as zombie process even `rosnode kill`-ed
I use `ros::spin` to spin ros service like followings:

```lisp
;; sample.l
(ros::roseus "foo")
(ros::spin)
```

```xml
<launch>
  <node name="sample" pkg="roseus" type="roseus" args="$(find bar_pkg)/sample.l"/>
</launch>
```

However when I run `rosnode kill /sample` to kill the roseus process, it is ignored.
(Actually, `/sample` is removed from rosgraph, but the process still exists as zombie process)

### PR DESCRIPTION
**Pull request by furushchev**
Closes #529

### CODE REVIEW

**Comment by furushchev** [comment]
With this PR, `roseus` is now successfully killed when `rosnode kill` is sent.

```lisp
[ WARN] [1499862652.848089678]: Shutdown request received.
[ WARN] [1499862652.848421583]: Reason given for shutdown: [user request]
Call Stack (max depth: 20):
  0: at (ros::spin)
  1: at #<compiled-code #X5398430>
/home/furushchev/ros/indigo_parent/devel/share/euslisp/jskeus/eus/Linux64/bin/irteusgl 0 error:  Shutdown requested in (ros::spin)
```

**Comment by k-okada** [comment]
If I look a code like 
https://github.com/ros/ros_comm/blob/ce4d7263138719590ca826fce02cae9f5bc3904a/clients/roscpp/src/libros/spinner.cpp#L139-L143
and tested with python like
```
$ cat sample.py 
#!/usr/bin/env python
import rospy
rospy.init_node('sample')
rospy.spin()
$ python -i ./sample.py 
shutdown request: user request
>>> 
```
I think
```
  while (ctx->intsig==0) {
     if ( ctx->intsig==0 && ros::ok() ) { 
      ros::spinOnce();
      s_rate->sleep();	
    }
```
seems better to me, but this does not terminate program unless you put '(ros::exit)', after the '(ros:spin)'

**Comment by furushchev** [comment]
@k-okada
If I understand correctly, you run with `-i` option that specifies interactive mode, that's why python does not exit.

Let me clarify:

### Python

- non interactive

```bash
$ python ./sample.py
shutdown request: user request
$ # now python exited
```

- interactive

```bash
$ python -i ./sample.py 
shutdown request: user request
>>> # Here shutdown is requested but python itself does not exit.
```

### Euslisp

- non interactive

```lisp
$ roseus ./sample.l __log:=aaaaa
configuring by "/home/furushchev/ros/indigo_parent/devel/share/euslisp/jskeus/eus//lib/eusrt.l"
;; readmacro ;; object ;; packsym ;; common ;; constants ;; stream ;; string ;; loader ;; pprint ;; process ;; hashtab ;; array ;; mathtran ;; eusdebug ;; eusforeign ;; coordinates ;; tty ;; history ;; toplevel ;; trans ;; comp ;; builtins ;; par ;; intersection ;; geoclasses ;; geopack ;; geobody ;; primt ;; compose ;; polygon ;; viewing ;; viewport ;; viewsurface ;; hid ;; shadow ;; bodyrel ;; dda ;; helpsub ;; eushelp ;; xforeign ;; Xdecl ;; Xgraphics ;; Xcolor ;; Xeus ;; Xevent ;; Xpanel ;; Xitem ;; Xtext ;; Xmenu ;; Xscroll ;; Xcanvas ;; Xtop ;; Xapplwin 
connected to Xserver DISPLAY=:0
X events are being asynchronously monitored.
;; pixword ;; RGBHLS ;; convolve ;; piximage ;; pbmfile ;; image_correlation ;; oglforeign ;; gldecl ;; glconst ;; glforeign ;; gluconst ;; gluforeign ;; glxconst ;; glxforeign ;; eglforeign ;; eglfunc ;; glutil ;; gltexture ;; glprim ;; gleus ;; glview ;; toiv-undefined ;; fstringdouble irtmath irtutil irtc irtgeoc irtgraph pgsql irtgeo euspqp pqp irtscene irtmodel irtdyna irtrobot irtsensor irtbvh irtcollada irtpointcloud irtx eusjpeg euspng png irtimage irtglrgb 
;; extending gcstack 0x51e0ad0[16374] --> 0x5640b40[32748] top=3d1c
irtgl irtglc irtviewer 
EusLisp 9.22(fc97a23 1.1.0) for Linux64 created on ThinkPad-P50(Tue Feb 21 13:17:37 JST 2017)
roseus ;; loading roseus("1.6.2-3-ga6d8eea") on euslisp((9.22 ThinkPad-P50 Tue Feb 21 13:17:37 JST 2017 fc97a23 1.1.0))
[ INFO] [1499932884.894971563]: install ros::roseus-sigint-handler
eustf roseus_c_util [ WARN] [1499932895.871780911]: Shutdown request received.
[ WARN] [1499932895.871823024]: Reason given for shutdown: [user request]
Call Stack (max depth: 20):
  0: at (ros::spin)
/home/furushchev/ros/indigo_parent/devel/share/euslisp/jskeus/eus/Linux64/bin/irteusgl roseus-error:  Shutdown requested in (ros::spin), exitting...
$ # now roseus exited 
```

- interactive

```lisp
$ roseus ./sample.l
configuring by "/home/furushchev/ros/indigo_parent/devel/share/euslisp/jskeus/eus//lib/eusrt.l"
;; readmacro ;; object ;; packsym ;; common ;; constants ;; stream ;; string ;; loader ;; pprint ;; process ;; hashtab ;; array ;; mathtran ;; eusdebug ;; eusforeign ;; coordinates ;; tty ;; history ;; toplevel ;; trans ;; comp ;; builtins ;; par ;; intersection ;; geoclasses ;; geopack ;; geobody ;; primt ;; compose ;; polygon ;; viewing ;; viewport ;; viewsurface ;; hid ;; shadow ;; bodyrel ;; dda ;; helpsub ;; eushelp ;; xforeign ;; Xdecl ;; Xgraphics ;; Xcolor ;; Xeus ;; Xevent ;; Xpanel ;; Xitem ;; Xtext ;; Xmenu ;; Xscroll ;; Xcanvas ;; Xtop ;; Xapplwin 
connected to Xserver DISPLAY=:0
X events are being asynchronously monitored.
;; pixword ;; RGBHLS ;; convolve ;; piximage ;; pbmfile ;; image_correlation ;; oglforeign ;; gldecl ;; glconst ;; glforeign ;; gluconst ;; gluforeign ;; glxconst ;; glxforeign ;; eglforeign ;; eglfunc ;; glutil ;; gltexture ;; glprim ;; gleus ;; glview ;; toiv-undefined ;; fstringdouble irtmath irtutil irtc irtgeoc irtgraph pgsql irtgeo euspqp pqp irtscene irtmodel irtdyna irtrobot irtsensor irtbvh irtcollada irtpointcloud irtx eusjpeg euspng png irtimage irtglrgb 
;; extending gcstack 0x4f9bad0[16374] --> 0x53fbb40[32748] top=3d1c
irtgl irtglc irtviewer 
EusLisp 9.22(fc97a23 1.1.0) for Linux64 created on ThinkPad-P50(Tue Feb 21 13:17:37 JST 2017)
roseus ;; loading roseus("1.6.2-3-ga6d8eea") on euslisp((9.22 ThinkPad-P50 Tue Feb 21 13:17:37 JST 2017 fc97a23 1.1.0))
eustf roseus_c_util [ WARN] [1499932796.916959903]: Shutdown request received.
[ WARN] [1499932796.917018991]: Reason given for shutdown: [user request]
Call Stack (max depth: 20):
  0: at (ros::spin)
/home/furushchev/ros/indigo_parent/devel/share/euslisp/jskeus/eus/Linux64/bin/irteusgl: ERROR th=0  0x7f53a98e4e1b in (ros::spin)E: 
;; here roseus itself is still alive.
```

**Comment by furushchev** [comment]
@k-okada Is it ok for you?

**Comment by furushchev** [comment]
Here are scripts that I used:

```python
$ cat sample.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Copyright: Yuki Furuta <furushchev@jsk.imi.i.u-tokyo.ac.jp>


import rospy
rospy.init_node("sample")
rospy.spin()
```

```lisp
$ cat sample.l
;; sample.l
;; Author: Yuki Furuta <furushchev@jsk.imi.i.u-tokyo.ac.jp>

(ros::roseus "sample")

(ros::spin)
```

**Comment by k-okada** [comment]
since roseus does not have 'non interactive mode', I think calling error
does not seems good specification, just to quit from `spin()` function and
ask users to write `ros:exit` explicitly. (or call ros::exit at the end of
spin function)

--
◉ Kei Okada


2017-07-13 17:05 GMT+09:00 Furushchev <notifications@github.com>:

**Comment by furushchev** [comment]
@k-okada Oh, I see. I'll then add `(ros::exit)` accordingly. Thanks for reviewing! :+1:

**Comment by furushchev** [comment]
Closed via #531

**Pull request closed without merging**
