### PR TITLE
[roseus_smach] fix transition fail when parallel state

### PR DESCRIPTION
**Pull request by furushchev**

### CODE REVIEW

**Comment by furushchev** [comment]
travis failed only on indigo/source

```
[jsk_roseus] CMake Error at /opt/ros/indigo/share/catkin/cmake/catkin_add_env_hooks.cmake:91 (file): 

[jsk_roseus]   file COPY cannot set modification time on                        

[jsk_roseus]   "/workspace/ros/ws_jsk_roseus/devel/etc/catkin/profile.d/05.catkin_make.bash" 

[jsk_roseus] Call Stack (most recent call first):                               

[jsk_roseus]   /opt/ros/indigo/share/catkin/cmake/all.cmake:198 (catkin_add_env_hooks) 

[jsk_roseus]   /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:20 (include) 

[jsk_roseus]   CMakeLists.txt:3 (find_package)                                  

[jsk_roseus]                                                                    

[jsk_roseus]                                                                    

[euslisp] -- gcc dumpmachine returns x86_64-linux-gnu                           

[geneus] -- Using these message generators: gencpp;genlisp;genpy                

[jsk_roseus] -- Configuring incomplete, errors occurred!                        

[jsk_roseus] See also "/workspace/ros/ws_jsk_roseus/build/jsk_roseus/CMakeFiles/CMakeOutput.log". 

[jsk_roseus] See also "/workspace/ros/ws_jsk_roseus/build/jsk_roseus/CMakeFiles/CMakeError.log". 

[jsk_roseus] <== '/workspace/ros/ws_jsk_roseus/build/jsk_roseus/build_env.sh /usr/bin/cmake /workspace/ros/ws_jsk_roseus/src/jsk_roseus/jsk_roseus -DCATKIN_DEVEL_PREFIX=/workspace/ros/ws_jsk_roseus/devel -DCMAKE_INSTALL_PREFIX=/workspace/ros/ws_jsk_roseus/install' failed with return code '1' 

Failed   <== jsk_roseus       [ 3.1 seconds ]  
```

**Comment by k-okada** [comment]
please use latest .travis, which download latest catkin 0.6.14 which fixed
copy problem

--
◉ Kei Okada

**Comment by k-okada** [comment]
https://github.com/jsk-ros-pkg/jsk_travis/tree/6f6b4f5dbc3a2fba4bc8a10d20d801e7ac3595df
 already uses latest catkin, so please check which version of catkin is
used from the log.

--
◉ Kei Okada

**Comment by k-okada** [comment]
your commit contains .travis which revert to old version, please update
them by
`git submodule update`

--
◉ Kei Okada

**Comment by furushchev** [comment]
Thanks to you, travis passed. Please merge!

**Pull request merged**
