### PR TITLE
add load-ros-manifest packages with dependencies option for downward compatibility

### PR DESCRIPTION
**Pull request by furushchev**
This is discussed at https://github.com/jsk-ros-pkg/jsk_recognition/issues/701
related with https://github.com/jsk-ros-pkg/jsk_smart_apps/issues/45

Since recent change on `euslisp/geneus`, only the packages that are listed as `generate_messages` at CMakeLists.txt are loaded by `(ros::load-ros-manifest pkg)`.
To generating all messages of `build_depends` packages makes build time so long, so I suggest to find dependent packages and load them on runtime.

### CODE REVIEW

**Comment by k-okada** [comment]
I think general rule is to use `load-ros-manifest`, but if you still wan to use `add-*`function, how about `ros::load-ros-manifest` within `ros::roseus-add-srvs`.

Also depending on other program is very dangerous.

**Comment by furushchev** [comment]
I know that general rule, I just mean that the behavior of all `ros::load-ros-manifest` and `ros::roses-add-*` function are changed.
But I also noticed that it may be not correct to add feature `with-deps` to `ros::load-ros-package` which is used in `manifest.l` because it inspects dependencies many time on one `ros::load-ros-manifest` execution.
So ok, I think it is good to add `with-deps` option into `ros::load-ros-manifest` function not `ros::load-ros-package`.

Also I intentionally implemented function that searching dependencies by Python, because I think it would be also dangerous that euslisp has "parsing `package.xml`" function, because package.xml has now 2 versions (http://docs.ros.org/api/catkin/html/) and is, I think, also still unstable.

**Comment by furushchev** [comment]
It is still incomplete, because it does not load dependencies' dependencies. I think we need to resolve all dependencies and ordering...

**Comment by k-okada** [comment]
Ok, let's create test codes, by extending https://github.com/jsk-ros-pkg/jsk_roseus/blob/master/roseus/test/test-genmsg.sh

**Comment by k-okada** [comment]
this problem is fixed in #249

**Pull request closed without merging**
