### PR TITLE
re-define get_string for osx

### PR DESCRIPTION
**Pull request by k-okada**
another implementation would be define get_string in eus.h as #define and write `#define get_string eus_get_string` in roseus.cpp, but I choose this PR since

- adding get_string to eus.h seems exceptional in other function/macro defined in eus.h
- ??

### CODE REVIEW

**Comment by wkentaro** [comment]
Thank you! :sparkles:

**Comment by wkentaro** [comment]
```
[roseus] rostest log file is in /home/travis/.ros/log/rostest-testing-gce-1a824012-326c-4c7e-b9bd-f3b0e60b05e0-14753.log
[roseus] -- run_tests.py: verify result "/home/travis/ros/ws_jsk_roseus/build/roseus/test_results/roseus/rostest-test_test-timer.xml"
[roseus] Built target _run_tests_roseus_rostest_test_test-timer.test
[roseus] Scanning dependencies of target _run_tests_roseus_rostest_test_test-talker-listener.test
[roseus] -- run_tests.py: execute commands
[roseus]   /opt/ros/hydro/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/travis/ros/ws_jsk_roseus/src/jsk_roseus/roseus --package=roseus --results-filename test_test-talker-listener.xml --results-dir /home/travis/ros/ws_jsk_roseus/build/roseus/test_results /home/travis/ros/ws_jsk_roseus/src/jsk_roseus/roseus/test/test-talker-listener.test
[roseus] Another rostest instance is currently running, waiting until it finished...
[roseus] ... logging to /home/travis/.ros/log/rostest-testing-gce-1a824012-326c-4c7e-b9bd-f3b0e60b05e0-14987.log
[roseus] [ROSUNIT] Outputting test results to /home/travis/ros/ws_jsk_roseus/build/roseus/test_results/roseus/rostest-test_test-actionlib.xml
[roseus] ;; loading roseus("411dd65") on euslisp((9.19 testing-gce-1a824012-326c-4c7e-b9bd-f3b0e60b05e0 Sun May 15 07:12:27 UTC 2016 88f1d01 1.0.10))
[roseus] ;; loading roseus("411dd65") on euslisp((9.19 testing-gce-1a824012-326c-4c7e-b9bd-f3b0e60b05e0 Sun May 15 07:12:27 UTC 2016 88f1d01 1.0.10))
[roseus] ;; loading roseus("411dd65") on euslisp((9.19 testing-gce-1a824012-326c-4c7e-b9bd-f3b0e60b05e0 Sun May 15 07:12:27 UTC 2016 88f1d01 1.0.10))
[roseus] ;; test-fibonacci 0/1000
[roseus] ;; 15541 wait-for-server
[roseus] output to /home/travis/.ros/test_results/roseus/rosunit-test_actionlib_client.xml
[roseus] start testing [wait-for-result-twice]
[roseus] ;; 15544 wait-for-server


No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

The build has been terminated
```

**Comment by k-okada** [comment]
can you run this on local environment?

--
◉ Kei Okada

**Comment by wkentaro** [comment]
It stops at `generate_eusdoc`.
```
ext ;; Xtext ;; Xtop ;; Xtop ;; Xmenu ;; Xscroll ;; Xmenu ;; Xcanvas ;; Xscroll ;; Xcanvas ;; Xapplwin ;; Xapplwin ;; Xtop ;; Xtop ;; Xapplwin ;; Xapplwin
[roseus] Xserver connection failed;; pixword ;; RGBHLS ;; convolve ;; piximage
[roseus] Xserver connection failed;; pixword ;; RGBHLS ;; convolve ;; piximage
[roseus] Xserver connection failed;; pixword ;; RGBHLS ;; convolve ;; piximage
[roseus] Xserver connection failed;; pixword ;; RGBHLS ;; convolve ;; piximage ;; pbmfile ;; image_correlation ;; oglforeign ;; pbmfile ;; image_correlation ;; oglforeign ;; pbmfile ;; image_correlation ;; oglforeign ;; pbmfile ;; image_correlation ;; oglforeign ;; gldecl ;; gldecl ;; glconst ;; gldecl ;; glconst ;; gldecl ;; glconst ;; glconst ;; glforeign ;; glforeign ;; gluconst ;; gluconst ;; gluforeign ;; gluforeign ;; glxconst ;; glxconst ;; glforeign ;; gluconst ;; gluforeign ;; glxconst ;; glforeign ;; gluconst ;; gluforeign ;; glxconst ;; glxforeign ;; eglforeign ;; eglfunc ;; glutil ;; gltexture ;; glprim ;; gleus ;; glview ;; glxforeign ;; eglforeign ;; eglfunc ;; glutil ;; glxforeign ;; gltexture ;; eglforeign ;; eglfunc ;; glutil ;; gltexture ;; glprim ;; glprim ;; toiv-undefined ;; fstringdouble ;; gleus ;; gleus ;; glview ;; glview ;; toiv-undefined ;; fstringdouble ;; toiv-undefined ;; fstringdouble irtmath irtutil ;; glxforeign ;; eglforeign ;; eglfunc ;; glutil ;; gltexture ;; glprim irtmath ;; gleus irtc ;; glview irtgeoc irtgraph irtmath irtutil irtutil ;; toiv-undefined ;; fstringdouble irtc irtgeoc irtgraph irtc irtgeoc irtgraph irtmath irtutil irtc irtgeoc irtgraph pgsql pgsql pgsql pgsql irtgeo euspqp pqp irtscene irtmodel irtgeo irtgeo irtgeo euspqp pqp irtscene euspqp pqp irtscene euspqp pqp irtscene irtmodel irtmodel irtmodel irtdyna irtdyna irtdyna irtdyna irtrobot irtsensor irtrobot irtrobot irtbvh irtsensor irtrobot irtsensor irtsensor irtbvh irtbvh irtbvh irtcollada irtpointcloud irtcollada irtx irtpointcloud irtcollada irtpointcloud irtx irtcollada irtx eusjpeg irtpointcloud euspng png irtimage irtglrgb eusjpeg irtx euspng png irtimage irtglrgb
[roseus] ;; extending gcstack 0x10f19d000[16374] --> 0x10f674000[32748] top=3f82
[roseus] eusjpeg euspng png irtimage irtglrgb eusjpeg
[roseus] ;; extending gcstack 0x109f77000[16374] --> 0x10a44e000[32748] top=3f82
[roseus] euspng png irtimage irtglrgb
[roseus] ;; extending gcstack 0x111f8e000[16374] --> 0x112465000[32748] top=3f82
[roseus]
[roseus] ;; extending gcstack 0x10b543000[16374] --> 0x10ba1a000[32748] top=3f82
[roseus] irtgl irtgl irtviewer irtgl irtviewer
[roseus] EusLisp 9.16(8f79f0c 8f79f0c) for Darwin created on elcapitanvm.local(Sun Nov 29 14:24:42 PST 2015)
[roseus] irtviewer irtgl
[roseus] EusLisp 9.16(8f79f0c 8f79f0c) for Darwin created on elcapitanvm.local(Sun Nov 29 14:24:42 PST 2015)
[roseus]
[roseus] EusLisp 9.16(8f79f0c 8f79f0c) for Darwin created on elcapitanvm.local(Sun Nov 29 14:24:42 PST 2015)
[roseus] irtviewer roseus ;; loading roseus("a1f22cf") on euslisp((9.16 elcapitanvm.local Sun Nov 29 14:24:42 PST 2015 8f79f0c 8f79f0c))
[roseus]
[roseus] EusLisp 9.16(8f79f0c 8f79f0c) for Darwin created on elcapitanvm.local(Sun Nov 29 14:24:42 PST 2015)
[roseus] roseus ;; loading roseus("a1f22cf") on euslisp((9.16 elcapitanvm.local Sun Nov 29 14:24:42 PST 2015 8f79f0c 8f79f0c))
[roseus] roseus ;; loading roseus("a1f22cf") on euslisp((9.16 elcapitanvm.local Sun Nov 29 14:24:42 PST 2015 8f79f0c 8f79f0c))
[roseus] eustf roseus ;; loading roseus("a1f22cf") on euslisp((9.16 elcapitanvm.local Sun Nov 29 14:24:42 PST 2015 8f79f0c 8f79f0c))
```

**Comment by wkentaro** [comment]
The build fixed via https://github.com/jsk-ros-pkg/jsk_roseus/pull/448/commits/ea4566e9b914508f32eaea648e53cbcbdfce5b32

**Pull request merged**
