### PR TITLE
[roseus_smach] func: make-state-machine accepts various edges

### PR DESCRIPTION
**Pull request by knorth55**
- `make-state-machine` accepts various edges
- set `testfunc` for transition in make-state-machine

### CODE REVIEW

**Comment by knorth55** [comment]
@furushchev thank you! I updated.

**Comment by furushchev** [comment]
@knorth55 Thanks! Could you also remove the comment `list` for avoiding confusion as we talked offline?

**Comment by knorth55** [comment]
@furushchev Updated!

**Comment by k-okada** [comment]
could add link to demo code using this feature.

**Comment by k-okada** [comment]
@knorth55 kindly ping

**Pull request merged**
